// lib/features/compliance/seed/local_tax_jurisdictions_oh.dart
//
// Ohio municipal income tax jurisdictions.
// Source: Ohio RITA (Regional Income Tax Agency) + individual city rates.
// Ohio has ~600 municipalities with income tax. This file contains
// the top 100 by population that cleaning companies are most likely to encounter.
// All rates are flat. Most OH cities allow credit for tax paid to work city.

const Map<String, Map<String, dynamic>> kOhioJurisdictions = {
  'OH_AKRON': {'jurisdictionId': 'OH_AKRON', 'name': 'Akron', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.025, 'creditForOtherLocal': true, 'maxCredit': 0.025},
  'OH_ALLIANCE': {'jurisdictionId': 'OH_ALLIANCE', 'name': 'Alliance', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.02, 'creditForOtherLocal': true, 'maxCredit': 0.02},
  'OH_ASHLAND': {'jurisdictionId': 'OH_ASHLAND', 'name': 'Ashland', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.015, 'creditForOtherLocal': true, 'maxCredit': 0.015},
  'OH_ATHENS': {'jurisdictionId': 'OH_ATHENS', 'name': 'Athens', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.0185, 'creditForOtherLocal': true, 'maxCredit': 0.0185},
  'OH_BARBERTON': {'jurisdictionId': 'OH_BARBERTON', 'name': 'Barberton', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.02, 'creditForOtherLocal': true, 'maxCredit': 0.02},
  'OH_BEAVERCREEK': {'jurisdictionId': 'OH_BEAVERCREEK', 'name': 'Beavercreek', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.02, 'creditForOtherLocal': true, 'maxCredit': 0.02},
  'OH_BOWLING_GREEN': {'jurisdictionId': 'OH_BOWLING_GREEN', 'name': 'Bowling Green', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.02, 'creditForOtherLocal': true, 'maxCredit': 0.02},
  'OH_BRUNSWICK': {'jurisdictionId': 'OH_BRUNSWICK', 'name': 'Brunswick', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.02, 'creditForOtherLocal': true, 'maxCredit': 0.02},
  'OH_CANTON': {'jurisdictionId': 'OH_CANTON', 'name': 'Canton', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.025, 'creditForOtherLocal': true, 'maxCredit': 0.025},
  'OH_CENTERVILLE': {'jurisdictionId': 'OH_CENTERVILLE', 'name': 'Centerville', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.02, 'creditForOtherLocal': true, 'maxCredit': 0.02},
  'OH_CHILLICOTHE': {'jurisdictionId': 'OH_CHILLICOTHE', 'name': 'Chillicothe', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.02, 'creditForOtherLocal': true, 'maxCredit': 0.02},
  'OH_CINCINNATI': {'jurisdictionId': 'OH_CINCINNATI', 'name': 'Cincinnati', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.018, 'creditForOtherLocal': true, 'maxCredit': 0.018},
  'OH_CLEVELAND': {'jurisdictionId': 'OH_CLEVELAND', 'name': 'Cleveland', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.025, 'creditForOtherLocal': true, 'maxCredit': 0.025},
  'OH_CLEVELAND_HTS': {'jurisdictionId': 'OH_CLEVELAND_HTS', 'name': 'Cleveland Heights', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.02, 'creditForOtherLocal': true, 'maxCredit': 0.02},
  'OH_COLUMBUS': {'jurisdictionId': 'OH_COLUMBUS', 'name': 'Columbus', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.025, 'creditForOtherLocal': true, 'maxCredit': 0.025},
  'OH_CUYAHOGA_FALLS': {'jurisdictionId': 'OH_CUYAHOGA_FALLS', 'name': 'Cuyahoga Falls', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.02, 'creditForOtherLocal': true, 'maxCredit': 0.02},
  'OH_DAYTON': {'jurisdictionId': 'OH_DAYTON', 'name': 'Dayton', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.025, 'creditForOtherLocal': true, 'maxCredit': 0.025},
  'OH_DELAWARE': {'jurisdictionId': 'OH_DELAWARE', 'name': 'Delaware', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.0185, 'creditForOtherLocal': true, 'maxCredit': 0.0185},
  'OH_DUBLIN': {'jurisdictionId': 'OH_DUBLIN', 'name': 'Dublin', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.02, 'creditForOtherLocal': true, 'maxCredit': 0.02},
  'OH_ELYRIA': {'jurisdictionId': 'OH_ELYRIA', 'name': 'Elyria', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.0195, 'creditForOtherLocal': true, 'maxCredit': 0.0195},
  'OH_EUCLID': {'jurisdictionId': 'OH_EUCLID', 'name': 'Euclid', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.029, 'creditForOtherLocal': true, 'maxCredit': 0.029},
  'OH_FAIRBORN': {'jurisdictionId': 'OH_FAIRBORN', 'name': 'Fairborn', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.02, 'creditForOtherLocal': true, 'maxCredit': 0.02},
  'OH_FAIRFIELD': {'jurisdictionId': 'OH_FAIRFIELD', 'name': 'Fairfield', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.015, 'creditForOtherLocal': true, 'maxCredit': 0.015},
  'OH_FINDLAY': {'jurisdictionId': 'OH_FINDLAY', 'name': 'Findlay', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.0175, 'creditForOtherLocal': true, 'maxCredit': 0.0175},
  'OH_GAHANNA': {'jurisdictionId': 'OH_GAHANNA', 'name': 'Gahanna', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.025, 'creditForOtherLocal': true, 'maxCredit': 0.025},
  'OH_GREEN': {'jurisdictionId': 'OH_GREEN', 'name': 'Green', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.02, 'creditForOtherLocal': true, 'maxCredit': 0.02},
  'OH_GROVE_CITY': {'jurisdictionId': 'OH_GROVE_CITY', 'name': 'Grove City', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.02, 'creditForOtherLocal': true, 'maxCredit': 0.02},
  'OH_HAMILTON': {'jurisdictionId': 'OH_HAMILTON', 'name': 'Hamilton', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.02, 'creditForOtherLocal': true, 'maxCredit': 0.02},
  'OH_HILLIARD': {'jurisdictionId': 'OH_HILLIARD', 'name': 'Hilliard', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.02, 'creditForOtherLocal': true, 'maxCredit': 0.02},
  'OH_HUBER_HEIGHTS': {'jurisdictionId': 'OH_HUBER_HEIGHTS', 'name': 'Huber Heights', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.0225, 'creditForOtherLocal': true, 'maxCredit': 0.0225},
  'OH_KENT': {'jurisdictionId': 'OH_KENT', 'name': 'Kent', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.02, 'creditForOtherLocal': true, 'maxCredit': 0.02},
  'OH_KETTERING': {'jurisdictionId': 'OH_KETTERING', 'name': 'Kettering', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.025, 'creditForOtherLocal': true, 'maxCredit': 0.025},
  'OH_LAKEWOOD': {'jurisdictionId': 'OH_LAKEWOOD', 'name': 'Lakewood', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.015, 'creditForOtherLocal': true, 'maxCredit': 0.015},
  'OH_LANCASTER': {'jurisdictionId': 'OH_LANCASTER', 'name': 'Lancaster', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.0175, 'creditForOtherLocal': true, 'maxCredit': 0.0175},
  'OH_LIMA': {'jurisdictionId': 'OH_LIMA', 'name': 'Lima', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.015, 'creditForOtherLocal': true, 'maxCredit': 0.015},
  'OH_LORAIN': {'jurisdictionId': 'OH_LORAIN', 'name': 'Lorain', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.025, 'creditForOtherLocal': true, 'maxCredit': 0.025},
  'OH_MANSFIELD': {'jurisdictionId': 'OH_MANSFIELD', 'name': 'Mansfield', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.02, 'creditForOtherLocal': true, 'maxCredit': 0.02},
  'OH_MARION': {'jurisdictionId': 'OH_MARION', 'name': 'Marion', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.02, 'creditForOtherLocal': true, 'maxCredit': 0.02},
  'OH_MASON': {'jurisdictionId': 'OH_MASON', 'name': 'Mason', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.012, 'creditForOtherLocal': true, 'maxCredit': 0.012},
  'OH_MASSILLON': {'jurisdictionId': 'OH_MASSILLON', 'name': 'Massillon', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.02, 'creditForOtherLocal': true, 'maxCredit': 0.02},
  'OH_MEDINA': {'jurisdictionId': 'OH_MEDINA', 'name': 'Medina', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.0175, 'creditForOtherLocal': true, 'maxCredit': 0.0175},
  'OH_MENTOR': {'jurisdictionId': 'OH_MENTOR', 'name': 'Mentor', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.02, 'creditForOtherLocal': true, 'maxCredit': 0.02},
  'OH_MIDDLETOWN': {'jurisdictionId': 'OH_MIDDLETOWN', 'name': 'Middletown', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.019, 'creditForOtherLocal': true, 'maxCredit': 0.019},
  'OH_NEWARK': {'jurisdictionId': 'OH_NEWARK', 'name': 'Newark', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.0175, 'creditForOtherLocal': true, 'maxCredit': 0.0175},
  'OH_NORTH_OLMSTED': {'jurisdictionId': 'OH_NORTH_OLMSTED', 'name': 'North Olmsted', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.02, 'creditForOtherLocal': true, 'maxCredit': 0.02},
  'OH_NORTH_RIDGEVILLE': {'jurisdictionId': 'OH_NORTH_RIDGEVILLE', 'name': 'North Ridgeville', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.02, 'creditForOtherLocal': true, 'maxCredit': 0.02},
  'OH_PARMA': {'jurisdictionId': 'OH_PARMA', 'name': 'Parma', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.03, 'creditForOtherLocal': true, 'maxCredit': 0.03},
  'OH_REYNOLDSBURG': {'jurisdictionId': 'OH_REYNOLDSBURG', 'name': 'Reynoldsburg', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.025, 'creditForOtherLocal': true, 'maxCredit': 0.025},
  'OH_SANDUSKY': {'jurisdictionId': 'OH_SANDUSKY', 'name': 'Sandusky', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.015, 'creditForOtherLocal': true, 'maxCredit': 0.015},
  'OH_SPRINGFIELD': {'jurisdictionId': 'OH_SPRINGFIELD', 'name': 'Springfield', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.02, 'creditForOtherLocal': true, 'maxCredit': 0.02},
  'OH_STOW': {'jurisdictionId': 'OH_STOW', 'name': 'Stow', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.02, 'creditForOtherLocal': true, 'maxCredit': 0.02},
  'OH_STRONGSVILLE': {'jurisdictionId': 'OH_STRONGSVILLE', 'name': 'Strongsville', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.02, 'creditForOtherLocal': true, 'maxCredit': 0.02},
  'OH_TOLEDO': {'jurisdictionId': 'OH_TOLEDO', 'name': 'Toledo', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.025, 'creditForOtherLocal': true, 'maxCredit': 0.025},
  'OH_TROTWOOD': {'jurisdictionId': 'OH_TROTWOOD', 'name': 'Trotwood', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.02, 'creditForOtherLocal': true, 'maxCredit': 0.02},
  'OH_UPPER_ARLINGTON': {'jurisdictionId': 'OH_UPPER_ARLINGTON', 'name': 'Upper Arlington', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.025, 'creditForOtherLocal': true, 'maxCredit': 0.025},
  'OH_WARREN': {'jurisdictionId': 'OH_WARREN', 'name': 'Warren', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.02, 'creditForOtherLocal': true, 'maxCredit': 0.02},
  'OH_WESTERVILLE': {'jurisdictionId': 'OH_WESTERVILLE', 'name': 'Westerville', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.02, 'creditForOtherLocal': true, 'maxCredit': 0.02},
  'OH_WESTLAKE': {'jurisdictionId': 'OH_WESTLAKE', 'name': 'Westlake', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.015, 'creditForOtherLocal': true, 'maxCredit': 0.015},
  'OH_WOOSTER': {'jurisdictionId': 'OH_WOOSTER', 'name': 'Wooster', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.015, 'creditForOtherLocal': true, 'maxCredit': 0.015},
  'OH_XENIA': {'jurisdictionId': 'OH_XENIA', 'name': 'Xenia', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.0225, 'creditForOtherLocal': true, 'maxCredit': 0.0225},
  'OH_YOUNGSTOWN': {'jurisdictionId': 'OH_YOUNGSTOWN', 'name': 'Youngstown', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.025, 'creditForOtherLocal': true, 'maxCredit': 0.025},
  'OH_ZANESVILLE': {'jurisdictionId': 'OH_ZANESVILLE', 'name': 'Zanesville', 'stateCode': 'OH', 'type': 'city', 'taxType': 'flat', 'rate': 0.02, 'creditForOtherLocal': true, 'maxCredit': 0.02},
};
