// lib/features/compliance/seed/payment_portal_directory_data.dart
//
// Directory of government payment portals where employers pay their taxes.
// Used by the Kleenops app to show customers exactly where to pay and when.
//
// Each entry provides:
//   portalUrl     — direct link to the payment page
//   portalName    — human-readable name
//   paymentMethod — 'ach_debit', 'ach_credit', 'web_portal', 'batch_file'
//   enrollmentUrl — where to enroll for electronic payments (if separate)
//   taxTypes      — what taxes can be paid here
//   filingUrl     — where to file returns (if different from payment)
//   notes         — enrollment requirements, thresholds, etc.

const Map<String, Map<String, dynamic>> kPaymentPortalDirectory = {
  // ════════════════════════════════════════════════════════════════
  // FEDERAL PAYMENT PORTALS
  // ════════════════════════════════════════════════════════════════

  'fed_eftps': {
    'level': 'federal',
    'portalName': 'EFTPS — Electronic Federal Tax Payment System',
    'portalUrl': 'https://www.eftps.gov/',
    'enrollmentUrl': 'https://www.eftps.gov/eftps/direct/EftpsHome.page',
    'paymentMethod': 'ach_debit',
    'taxTypes': [
      'federal_income_withholding',
      'social_security',
      'medicare',
      'futa',
    ],
    'forms': ['941', '940', '944', '945'],
    'enrollmentRequirements': [
      'EIN required',
      'Business bank account',
      'Enrollment takes 5-15 business days (PIN mailed)',
    ],
    'cutoffTime': '8:00 PM ET for next-business-day settlement',
    'notes': 'Primary system for all federal tax deposits. '
        'Mandatory for businesses with >200K annual tax liability. '
        'Free to use.',
  },
  'fed_irs_directpay': {
    'level': 'federal',
    'portalName': 'IRS Direct Pay',
    'portalUrl': 'https://www.irs.gov/payments/direct-pay',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['federal_income_withholding'],
    'forms': ['941', '940'],
    'notes': 'Alternative to EFTPS for individual payments. '
        'No enrollment required. '
        'Payments limited to certain form types.',
  },
  'fed_ssa_bso': {
    'level': 'federal',
    'portalName': 'SSA Business Services Online (W-2 Filing)',
    'portalUrl': 'https://www.ssa.gov/bso/bsowelcome.htm',
    'enrollmentUrl': 'https://www.ssa.gov/bso/',
    'paymentMethod': 'file_upload',
    'taxTypes': ['w2_filing'],
    'forms': ['W-2', 'W-3', 'W-2c'],
    'fileFormat': 'EFW2 fixed-width flat file',
    'notes': 'Upload W-2 data electronically. '
        'Mandatory for 250+ W-2s. '
        'Free AccuWage tool validates files before submission.',
  },
  'fed_irs_fire': {
    'level': 'federal',
    'portalName': 'IRS FIRE System (1099 Filing)',
    'portalUrl': 'https://fire.irs.gov/',
    'enrollmentUrl': 'https://fire.irs.gov/',
    'paymentMethod': 'file_upload',
    'taxTypes': ['1099_filing'],
    'forms': ['1099-NEC', '1099-MISC', '1099-K'],
    'fileFormat': 'Publication 1220 fixed-width flat file',
    'enrollmentRequirements': [
      'Transmitter Control Code (TCC) required',
      'Apply via IRS Form 4419 or IR Application for TCC',
    ],
    'notes': 'Mandatory for 10+ information returns. '
        'Combined Federal/State Filing Program forwards 1099s to ~40 participating states.',
  },

  // ════════════════════════════════════════════════════════════════
  // STATE PAYMENT PORTALS
  // ════════════════════════════════════════════════════════════════

  'AL': {
    'level': 'state',
    'stateCode': 'AL',
    'stateName': 'Alabama',
    'portalName': 'My Alabama Taxes (MAT)',
    'portalUrl': 'https://myalabamataxes.alabama.gov/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding', 'sui'],
    'withholdingForms': ['A-6 (Quarterly)', 'A-1 (Annual Reconciliation)'],
    'suiPortalUrl': 'https://labor.alabama.gov/uc/',
    'suiPortalName': 'UC Employer Services',
  },
  'AK': {
    'level': 'state',
    'stateCode': 'AK',
    'stateName': 'Alaska',
    'portalName': 'Alaska Employer Tax Portal',
    'portalUrl': 'https://labor.alaska.gov/estax/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['sui'],
    'hasStateIncomeTax': false,
    'notes': 'No state income tax. SUI only.',
  },
  'AZ': {
    'level': 'state',
    'stateCode': 'AZ',
    'stateName': 'Arizona',
    'portalName': 'AZTaxes.gov',
    'portalUrl': 'https://aztaxes.gov/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['A1-QRT (Quarterly)', 'A1-R (Annual Reconciliation)'],
    'suiPortalUrl': 'https://des.az.gov/services/employment/unemployment-employer',
    'suiPortalName': 'DES Employer UI',
  },
  'AR': {
    'level': 'state',
    'stateCode': 'AR',
    'stateName': 'Arkansas',
    'portalName': 'ATAP — Arkansas Taxpayer Access Point',
    'portalUrl': 'https://atap.arkansas.gov/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding', 'sui'],
    'withholdingForms': ['AR941M (Monthly)', 'AR3MAR (Quarterly Reconciliation)'],
  },
  'CA': {
    'level': 'state',
    'stateCode': 'CA',
    'stateName': 'California',
    'portalName': 'EDD e-Services for Business',
    'portalUrl': 'https://edd.ca.gov/en/payroll_taxes/e-Services_for_Business/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding', 'sui', 'sdi', 'ett'],
    'withholdingForms': ['DE 9 (Quarterly)', 'DE 9C (Quarterly Detail)'],
    'suiPortalUrl': 'https://edd.ca.gov/en/payroll_taxes/e-Services_for_Business/',
    'suiPortalName': 'EDD e-Services (same portal)',
    'notes': 'California combines withholding, SUI, SDI, and ETT into one portal. '
        'Mandatory e-pay for employers depositing >80K/year.',
  },
  'CO': {
    'level': 'state',
    'stateCode': 'CO',
    'stateName': 'Colorado',
    'portalName': 'Revenue Online',
    'portalUrl': 'https://www.colorado.gov/revenueonline/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding', 'famli'],
    'withholdingForms': ['DR 1094 (Quarterly)'],
    'suiPortalUrl': 'https://myui.coworkforce.com/',
    'suiPortalName': 'MyUI Employer',
    'notes': 'Colorado also has FAMLI (Family and Medical Leave Insurance) payroll tax.',
  },
  'CT': {
    'level': 'state',
    'stateCode': 'CT',
    'stateName': 'Connecticut',
    'portalName': 'myconneCT',
    'portalUrl': 'https://portal.ct.gov/DRS/myconneCT/myconneCT',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['CT-941 (Quarterly)'],
    'suiPortalUrl': 'https://www.ctdol.state.ct.us/uitax/',
    'suiPortalName': 'CT DOL Employer Tax',
  },
  'DE': {
    'level': 'state',
    'stateCode': 'DE',
    'stateName': 'Delaware',
    'portalName': 'Delaware Employer Portal',
    'portalUrl': 'https://revenue.delaware.gov/employers/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['W1 (Monthly/Quarterly)'],
    'suiPortalUrl': 'https://ui.delawareworks.com/',
    'suiPortalName': 'UI Employer Services',
  },
  'FL': {
    'level': 'state',
    'stateCode': 'FL',
    'stateName': 'Florida',
    'portalName': 'Florida Reemployment Tax Portal',
    'portalUrl': 'https://floridarevenue.com/taxes/eservices/Pages/default.aspx',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['sui'],
    'hasStateIncomeTax': false,
    'suiPortalUrl': 'https://floridarevenue.com/taxes/eservices/Pages/default.aspx',
    'suiPortalName': 'FL DOR e-Services (RT-6)',
    'notes': 'No state income tax. Reemployment (SUI) tax only.',
  },
  'GA': {
    'level': 'state',
    'stateCode': 'GA',
    'stateName': 'Georgia',
    'portalName': 'Georgia Tax Center (GTC)',
    'portalUrl': 'https://gtc.dor.ga.gov/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['G-7 (Quarterly)'],
    'suiPortalUrl': 'https://dol.georgia.gov/employers',
    'suiPortalName': 'GA DOL Employer Portal',
  },
  'HI': {
    'level': 'state',
    'stateCode': 'HI',
    'stateName': 'Hawaii',
    'portalName': 'Hawaii Tax Online',
    'portalUrl': 'https://hitax.hawaii.gov/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['VP-1 (Monthly)'],
    'suiPortalUrl': 'https://huiclaims.hawaii.gov/',
    'suiPortalName': 'HUI Employer Services',
  },
  'ID': {
    'level': 'state',
    'stateCode': 'ID',
    'stateName': 'Idaho',
    'portalName': 'Idaho TAP (Taxpayer Access Point)',
    'portalUrl': 'https://tax.idaho.gov/taxes/withholding/paying-withholding-tax/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['910 (Monthly)'],
    'suiPortalUrl': 'https://www.labor.idaho.gov/dnn/Employer-Resources',
    'suiPortalName': 'IDOL Employer Services',
  },
  'IL': {
    'level': 'state',
    'stateCode': 'IL',
    'stateName': 'Illinois',
    'portalName': 'MyTax Illinois',
    'portalUrl': 'https://mytax.illinois.gov/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['IL-941 (Quarterly)'],
    'suiPortalUrl': 'https://ides.illinois.gov/employers.html',
    'suiPortalName': 'IDES Employer Portal',
  },
  'IN': {
    'level': 'state',
    'stateCode': 'IN',
    'stateName': 'Indiana',
    'portalName': 'INTIME — Indiana Taxpayer Information Management Engine',
    'portalUrl': 'https://intime.dor.in.gov/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding', 'county_income_tax'],
    'withholdingForms': ['WH-1 (Monthly)', 'WH-3 (Annual Reconciliation)'],
    'suiPortalUrl': 'https://uplink.in.gov/',
    'suiPortalName': 'Uplink Employer Self-Service',
    'notes': 'Indiana county taxes are remitted through the same state portal.',
  },
  'IA': {
    'level': 'state',
    'stateCode': 'IA',
    'stateName': 'Iowa',
    'portalName': 'GovConnectIowa',
    'portalUrl': 'https://tax.iowa.gov/GovConnectIowa',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['44-095 (Quarterly)'],
    'suiPortalUrl': 'https://www.myiowaui.org/',
    'suiPortalName': 'myIowaUI Employer Portal',
  },
  'KS': {
    'level': 'state',
    'stateCode': 'KS',
    'stateName': 'Kansas',
    'portalName': 'Kansas Customer Service Center',
    'portalUrl': 'https://www.kdor.ks.gov/apps/kcsc/login.aspx',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['KW-5 (Monthly/Quarterly)'],
    'suiPortalUrl': 'https://www.getkansasbenefits.gov/',
    'suiPortalName': 'Kansas UI Employer Services',
  },
  'KY': {
    'level': 'state',
    'stateCode': 'KY',
    'stateName': 'Kentucky',
    'portalName': 'Kentucky Online Gateway (KOG)',
    'portalUrl': 'https://onestop.ky.gov/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['K-1 (Quarterly)'],
    'suiPortalUrl': 'https://kewes.ky.gov/',
    'suiPortalName': 'KEWES Employer Self-Service',
    'localTaxNotes': 'Local occupational taxes are paid separately to each city/county.',
  },
  'LA': {
    'level': 'state',
    'stateCode': 'LA',
    'stateName': 'Louisiana',
    'portalName': 'Louisiana Taxpayer Access Point (LaTAP)',
    'portalUrl': 'https://latap.revenue.louisiana.gov/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['L-1 (Quarterly)'],
    'suiPortalUrl': 'https://www.laworks.net/PublicPages/EmployerServices.aspx',
    'suiPortalName': 'LWC Employer Services',
  },
  'ME': {
    'level': 'state',
    'stateCode': 'ME',
    'stateName': 'Maine',
    'portalName': 'Maine EZ Pay',
    'portalUrl': 'https://portal.maine.gov/ezpay/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['941ME (Quarterly)'],
    'suiPortalUrl': 'https://gateway.maine.gov/rebgw/',
    'suiPortalName': 'ReEmployment Benefits Gateway',
  },
  'MD': {
    'level': 'state',
    'stateCode': 'MD',
    'stateName': 'Maryland',
    'portalName': 'bFile — Maryland Online Tax Filing',
    'portalUrl': 'https://interactive.marylandtaxes.gov/business/bfile/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding', 'county_income_tax'],
    'withholdingForms': ['MW506 (Monthly/Quarterly)', 'MW508 (Annual Reconciliation)'],
    'suiPortalUrl': 'https://www.uitax.dllr.state.md.us/',
    'suiPortalName': 'DLLR UI Tax Portal',
    'notes': 'County piggyback taxes are remitted with state withholding through the same portal.',
  },
  'MA': {
    'level': 'state',
    'stateCode': 'MA',
    'stateName': 'Massachusetts',
    'portalName': 'MassTaxConnect',
    'portalUrl': 'https://mtc.dor.state.ma.us/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding', 'pfml'],
    'withholdingForms': ['M-941 (Quarterly)'],
    'suiPortalUrl': 'https://uionline.detma.org/Employer/',
    'suiPortalName': 'DUA Employer Portal',
    'notes': 'Massachusetts also has Paid Family and Medical Leave (PFML) payroll tax.',
  },
  'MI': {
    'level': 'state',
    'stateCode': 'MI',
    'stateName': 'Michigan',
    'portalName': 'Michigan Treasury Online (MTO)',
    'portalUrl': 'https://mto.treasury.michigan.gov/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['5080 (Monthly/Quarterly)', '5081 (Annual Reconciliation)'],
    'suiPortalUrl': 'https://miwam.unemployment.state.mi.us/',
    'suiPortalName': 'MiWAM Employer',
    'localTaxNotes': 'City income taxes are paid separately to each city (e.g., Detroit, Grand Rapids).',
  },
  'MN': {
    'level': 'state',
    'stateCode': 'MN',
    'stateName': 'Minnesota',
    'portalName': 'Minnesota e-Services',
    'portalUrl': 'https://www.mndor.state.mn.us/tp/eservices/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['MW-5 (Quarterly)'],
    'suiPortalUrl': 'https://uimn.org/employers/',
    'suiPortalName': 'UIMN Employer Portal',
  },
  'MS': {
    'level': 'state',
    'stateCode': 'MS',
    'stateName': 'Mississippi',
    'portalName': 'Mississippi TAP',
    'portalUrl': 'https://tap.dor.ms.gov/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['89-105 (Monthly/Quarterly)'],
    'suiPortalUrl': 'https://mdes.ms.gov/employers/',
    'suiPortalName': 'MDES Employer Services',
  },
  'MO': {
    'level': 'state',
    'stateCode': 'MO',
    'stateName': 'Missouri',
    'portalName': 'Missouri Tax Portal',
    'portalUrl': 'https://mytax.mo.gov/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['MO-941 (Quarterly)'],
    'suiPortalUrl': 'https://uinteract.labor.mo.gov/',
    'suiPortalName': 'UInteract Employer Portal',
  },
  'MT': {
    'level': 'state',
    'stateCode': 'MT',
    'stateName': 'Montana',
    'portalName': 'Montana TransAction Portal (TAP)',
    'portalUrl': 'https://tap.dor.mt.gov/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['MW-1 (Quarterly)'],
    'suiPortalUrl': 'https://uid.dli.mt.gov/',
    'suiPortalName': 'DLI UI Employer Portal',
  },
  'NE': {
    'level': 'state',
    'stateCode': 'NE',
    'stateName': 'Nebraska',
    'portalName': 'Nebraska e-Pay',
    'portalUrl': 'https://revenue.nebraska.gov/businesses/e-pay',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['941N (Quarterly)'],
    'suiPortalUrl': 'https://neworks.nebraska.gov/',
    'suiPortalName': 'NEworks Employer Services',
  },
  'NV': {
    'level': 'state',
    'stateCode': 'NV',
    'stateName': 'Nevada',
    'portalName': 'Nevada Employer Portal',
    'portalUrl': 'https://ui.nv.gov/EMPLOYER/EmployerHomePage.html',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['sui'],
    'hasStateIncomeTax': false,
    'suiPortalUrl': 'https://ui.nv.gov/EMPLOYER/EmployerHomePage.html',
    'suiPortalName': 'DETR Employer Services',
    'notes': 'No state income tax. SUI only.',
  },
  'NH': {
    'level': 'state',
    'stateCode': 'NH',
    'stateName': 'New Hampshire',
    'portalName': 'NH Employment Security',
    'portalUrl': 'https://www.nhes.nh.gov/services/employers/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['sui'],
    'hasStateIncomeTax': false,
    'suiPortalUrl': 'https://www.nhes.nh.gov/services/employers/',
    'suiPortalName': 'NHES Employer Services',
    'notes': 'No wage income tax. SUI only.',
  },
  'NJ': {
    'level': 'state',
    'stateCode': 'NJ',
    'stateName': 'New Jersey',
    'portalName': 'NJ Online Filing',
    'portalUrl': 'https://www1.state.nj.us/TYTR_BusinessFilings/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding', 'sui', 'sdi', 'fli', 'wf'],
    'withholdingForms': ['NJ-927 (Quarterly)', 'NJ-W3 (Annual Reconciliation)'],
    'suiPortalUrl': 'https://www1.state.nj.us/TYTR_BusinessFilings/',
    'suiPortalName': 'NJ combined filing (same portal)',
    'notes': 'NJ combines withholding, SUI, SDI, FLI, and WF/SWF into one quarterly filing.',
  },
  'NM': {
    'level': 'state',
    'stateCode': 'NM',
    'stateName': 'New Mexico',
    'portalName': 'New Mexico Taxpayer Access Point (TAP)',
    'portalUrl': 'https://tap.state.nm.us/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['CRS-1 (Quarterly)'],
    'suiPortalUrl': 'https://www.jobs.state.nm.us/employer/',
    'suiPortalName': 'NMDWS Employer Services',
  },
  'NY': {
    'level': 'state',
    'stateCode': 'NY',
    'stateName': 'New York',
    'portalName': 'NYS Online Services',
    'portalUrl': 'https://www.tax.ny.gov/online/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['NYS-45 (Quarterly Combined)'],
    'suiPortalUrl': 'https://www.tax.ny.gov/online/',
    'suiPortalName': 'NYS Online Services (combined NYS-45)',
    'notes': 'PrompTax program mandatory for employers with >15K/quarter. '
        'NYC and Yonkers withholding included in state filing.',
    'localTaxNotes': 'NYC and Yonkers taxes filed through the same NYS-45.',
  },
  'NC': {
    'level': 'state',
    'stateCode': 'NC',
    'stateName': 'North Carolina',
    'portalName': 'NCDOR eFile',
    'portalUrl': 'https://eservices.dor.nc.gov/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['NC-5 (Monthly/Quarterly)'],
    'suiPortalUrl': 'https://des.nc.gov/employers',
    'suiPortalName': 'DES Employer Portal',
  },
  'ND': {
    'level': 'state',
    'stateCode': 'ND',
    'stateName': 'North Dakota',
    'portalName': 'ND TAP (Taxpayer Access Point)',
    'portalUrl': 'https://apps.nd.gov/tax/tap/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['306 (Quarterly)'],
    'suiPortalUrl': 'https://www.jobsnd.com/employer-services',
    'suiPortalName': 'Job Service ND Employer',
  },
  'OH': {
    'level': 'state',
    'stateCode': 'OH',
    'stateName': 'Ohio',
    'portalName': 'Ohio Business Gateway',
    'portalUrl': 'https://gateway.ohio.gov/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['IT 941 (Quarterly)'],
    'suiPortalUrl': 'https://unemployment.ohio.gov/employer/',
    'suiPortalName': 'Ohio UI Employer Portal',
    'localTaxNotes': 'Municipal taxes paid separately. '
        'RITA: https://www.ritaohio.com/ — covers ~300 municipalities. '
        'CCA: https://www.ccatax.ci.cleveland.oh.us/ — covers Cleveland area.',
    'localPortals': [
      {
        'name': 'RITA (Regional Income Tax Agency)',
        'url': 'https://www.ritaohio.com/',
        'description': '~300 Ohio municipalities',
      },
      {
        'name': 'CCA (Central Collection Agency)',
        'url': 'https://www.ccatax.ci.cleveland.oh.us/',
        'description': 'Cleveland and surrounding cities',
      },
    ],
  },
  'OK': {
    'level': 'state',
    'stateCode': 'OK',
    'stateName': 'Oklahoma',
    'portalName': 'Oklahoma Taxpayer Access Point',
    'portalUrl': 'https://oktap.tax.ok.gov/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['WTH-10004 (Quarterly)'],
    'suiPortalUrl': 'https://unemployment.state.ok.us/EmpPortal/',
    'suiPortalName': 'OESC Employer Portal',
  },
  'OR': {
    'level': 'state',
    'stateCode': 'OR',
    'stateName': 'Oregon',
    'portalName': 'Revenue Online',
    'portalUrl': 'https://revenueonline.dor.oregon.gov/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding', 'transit_tax'],
    'withholdingForms': ['OQ (Quarterly Combined)', 'OR-WR (Annual Reconciliation)'],
    'suiPortalUrl': 'https://www.oregon.gov/employ/businesses/pages/employer-account.aspx',
    'suiPortalName': 'OED Employer Account',
    'notes': 'Oregon statewide transit tax (0.1%) is included in the combined OQ filing.',
  },
  'PA': {
    'level': 'state',
    'stateCode': 'PA',
    'stateName': 'Pennsylvania',
    'portalName': 'myPATH',
    'portalUrl': 'https://mypath.pa.gov/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['PA-W3 (Quarterly Reconciliation)'],
    'suiPortalUrl': 'https://www.uc.pa.gov/employers-uc-services-uc-tax/',
    'suiPortalName': 'UC Management System',
    'localTaxNotes': 'Local EIT is paid to Act 32 tax officers (Berkheimer, Keystone, Jordan, etc.), '
        'NOT through the state portal.',
    'localPortals': [
      {
        'name': 'Berkheimer Tax Administrator',
        'url': 'https://www.hab-inc.com/',
        'description': 'Largest Act 32 collector',
      },
      {
        'name': 'Keystone Collections Group',
        'url': 'https://www.keystonecollects.com/',
        'description': 'Second-largest Act 32 collector',
      },
      {
        'name': 'Jordan Tax Service',
        'url': 'https://www.jordantax.com/',
        'description': 'Western PA collector',
      },
    ],
  },
  'RI': {
    'level': 'state',
    'stateCode': 'RI',
    'stateName': 'Rhode Island',
    'portalName': 'Rhode Island Tax Portal',
    'portalUrl': 'https://taxportal.ri.gov/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['RI-941 (Quarterly)'],
    'suiPortalUrl': 'https://dlt.ri.gov/employers',
    'suiPortalName': 'DLT Employer Services',
  },
  'SC': {
    'level': 'state',
    'stateCode': 'SC',
    'stateName': 'South Carolina',
    'portalName': 'MyDORWAY',
    'portalUrl': 'https://mydorway.dor.sc.gov/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['WH-1605 (Quarterly)'],
    'suiPortalUrl': 'https://uitax.dew.sc.gov/',
    'suiPortalName': 'DEW Employer Tax Portal',
  },
  'SD': {
    'level': 'state',
    'stateCode': 'SD',
    'stateName': 'South Dakota',
    'portalName': 'SD DLR Employer Services',
    'portalUrl': 'https://dlr.sd.gov/unemployment_insurance/ui_employers.aspx',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['sui'],
    'hasStateIncomeTax': false,
    'suiPortalUrl': 'https://dlr.sd.gov/unemployment_insurance/ui_employers.aspx',
    'suiPortalName': 'DLR Employer Services',
    'notes': 'No state income tax. SUI only.',
  },
  'TN': {
    'level': 'state',
    'stateCode': 'TN',
    'stateName': 'Tennessee',
    'portalName': 'TN Employer Portal',
    'portalUrl': 'https://www.tn.gov/workforce/employers/tax-and-insurance.html',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['sui'],
    'hasStateIncomeTax': false,
    'suiPortalUrl': 'https://www.jobs4tn.gov/',
    'suiPortalName': 'Jobs4TN Employer Services',
    'notes': 'No wage income tax. SUI only.',
  },
  'TX': {
    'level': 'state',
    'stateCode': 'TX',
    'stateName': 'Texas',
    'portalName': 'TWC Employer Portal',
    'portalUrl': 'https://www.twc.texas.gov/businesses/unemployment-tax',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['sui'],
    'hasStateIncomeTax': false,
    'suiPortalUrl': 'https://www.twc.texas.gov/businesses/unemployment-tax',
    'suiPortalName': 'TWC UI Tax Services',
    'notes': 'No state income tax. SUI only.',
  },
  'UT': {
    'level': 'state',
    'stateCode': 'UT',
    'stateName': 'Utah',
    'portalName': 'Utah Taxpayer Access Point (TAP)',
    'portalUrl': 'https://tap.tax.utah.gov/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['TC-941 (Quarterly)'],
    'suiPortalUrl': 'https://jobs.utah.gov/employer/',
    'suiPortalName': 'DWS Employer Portal',
  },
  'VT': {
    'level': 'state',
    'stateCode': 'VT',
    'stateName': 'Vermont',
    'portalName': 'myVTax',
    'portalUrl': 'https://myvtax.vermont.gov/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['WHT-436 (Quarterly)'],
    'suiPortalUrl': 'https://labor.vermont.gov/employers',
    'suiPortalName': 'VDOL Employer Services',
  },
  'VA': {
    'level': 'state',
    'stateCode': 'VA',
    'stateName': 'Virginia',
    'portalName': 'Virginia Tax Online Services',
    'portalUrl': 'https://www.individual.tax.virginia.gov/VTOL/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['VA-5 (Monthly/Quarterly)'],
    'suiPortalUrl': 'https://www.vec.virginia.gov/employers',
    'suiPortalName': 'VEC Employer Portal',
  },
  'WA': {
    'level': 'state',
    'stateCode': 'WA',
    'stateName': 'Washington',
    'portalName': 'WA ESD Employer Portal',
    'portalUrl': 'https://esd.wa.gov/employer-taxes',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['sui', 'wa_cares', 'pfml'],
    'hasStateIncomeTax': false,
    'suiPortalUrl': 'https://esd.wa.gov/employer-taxes',
    'suiPortalName': 'ESD Employer Tax Services',
    'notes': 'No income tax. Has SUI, WA Cares Fund (long-term care), and PFML payroll taxes.',
  },
  'WV': {
    'level': 'state',
    'stateCode': 'WV',
    'stateName': 'West Virginia',
    'portalName': 'WV MyTaxes',
    'portalUrl': 'https://mytaxes.wvtax.gov/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['WV/IT-101 (Quarterly)'],
    'suiPortalUrl': 'https://workforcewv.org/employers/',
    'suiPortalName': 'WorkForce WV Employer',
  },
  'WI': {
    'level': 'state',
    'stateCode': 'WI',
    'stateName': 'Wisconsin',
    'portalName': 'My Tax Account',
    'portalUrl': 'https://tap.revenue.wi.gov/mta/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding'],
    'withholdingForms': ['WT-6 (Quarterly)'],
    'suiPortalUrl': 'https://dwd.wisconsin.gov/uitax/',
    'suiPortalName': 'DWD Employer UI Tax',
  },
  'WY': {
    'level': 'state',
    'stateCode': 'WY',
    'stateName': 'Wyoming',
    'portalName': 'WY DWS Employer Services',
    'portalUrl': 'https://dws.wyo.gov/employers/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['sui'],
    'hasStateIncomeTax': false,
    'suiPortalUrl': 'https://dws.wyo.gov/employers/',
    'suiPortalName': 'DWS Employer Services',
    'notes': 'No state income tax. SUI only.',
  },
  'DC': {
    'level': 'state',
    'stateCode': 'DC',
    'stateName': 'District of Columbia',
    'portalName': 'MyTax.DC.gov',
    'portalUrl': 'https://mytax.dc.gov/',
    'paymentMethod': 'ach_debit',
    'taxTypes': ['state_income_withholding', 'pfml'],
    'withholdingForms': ['FR-900Q (Quarterly)'],
    'suiPortalUrl': 'https://does.dc.gov/service/employer-tax-information',
    'suiPortalName': 'DOES Employer Tax',
    'notes': 'DC also has Paid Family Leave (PFL) payroll tax.',
  },
};
