// lib/features/compliance/seed/state_seed_data.dart
//
// All 50 US states + DC employment rules for cleaning businesses.
// Sources: DOL state pages, state labor dept websites, NFIB state guides.
// Data reflects 2025-2026 rates; update annually.
//
// Key fields per state:
//   minimumWage, hasStateIncomeTax, stateTaxType, workersCompRequired,
//   sutaRateNew, paidSickLeave, businessRegistration, etc.

const Map<String, Map<String, dynamic>> kStateRules = {
  // ════════════════════════════════════════════════════════════════
  'AL': {
    'stateCode': 'AL',
    'stateName': 'Alabama',
    'effectiveYear': 2026,
    'minimumWage': 7.25, // follows federal
    'tippedMinimumWage': 2.13,
    'overtimeThreshold': 40,
    'overtimeMultiplier': 1.5,
    'hasStateIncomeTax': true,
    'stateTaxType': 'graduated',
    'taxBrackets': [
      {'min': 0, 'max': 500, 'rate': 0.02},
      {'min': 500, 'max': 3000, 'rate': 0.04},
      {'min': 3000, 'max': 999999999, 'rate': 0.05},
    ],
    'depositSchedule': 'quarterly',
    'sutaRateNew': 0.027,
    'sutaRateMin': 0.005,
    'sutaRateMax': 0.068,
    'sutaWageCap': 8000,
    'sutaRegistrationUrl': 'https://labor.alabama.gov/uc/',
    'workersCompRequired': true,
    'workersCompExemptions': 'Employers with fewer than 5 employees may be exempt',
    'workersCompCleaningRate': 0.035,
    'workersCompUrl': 'https://labor.alabama.gov/wc/',
    'benefitsThresholdHours': 30,
    'benefitsThresholdType': 'weekly',
    'paidSickLeave': {'required': false},
    'atWillEmployment': true,
    'rightToWork': true,
    'eVerifyRequired': false,
    'businessRegistration': {
      'secretaryOfStateUrl': 'https://www.sos.alabama.gov/',
      'businessLicenseRequired': true,
      'businessLicenseUrl': 'https://www.sos.alabama.gov/business-services',
      'janitoralLicenseRequired': false,
      'bondRequired': false,
    },
    'requiredPostings': [
      {'name': 'Alabama Child Labor Law', 'url': 'https://labor.alabama.gov/'},
      {'name': 'Alabama Workers Comp Notice', 'url': 'https://labor.alabama.gov/wc/'},
    ],
    'taxFilingSchedule': [
      {'formId': 'A-6', 'name': 'Employer Quarterly Return', 'frequency': 'quarterly'},
    ],
  },

  'AK': {
    'stateCode': 'AK',
    'stateName': 'Alaska',
    'effectiveYear': 2026,
    'minimumWage': 11.73,
    'overtimeThreshold': 40,
    'overtimeMultiplier': 1.5,
    'hasStateIncomeTax': false,
    'stateTaxType': 'none',
    'sutaRateNew': 0.021,
    'sutaRateMin': 0.01,
    'sutaRateMax': 0.054,
    'sutaWageCap': 47100,
    'sutaRegistrationUrl': 'https://labor.alaska.gov/estax/',
    'workersCompRequired': true,
    'workersCompCleaningRate': 0.038,
    'workersCompUrl': 'https://labor.alaska.gov/wc/',
    'paidSickLeave': {'required': false},
    'atWillEmployment': true,
    'rightToWork': false,
    'eVerifyRequired': false,
    'businessRegistration': {
      'secretaryOfStateUrl': 'https://www.commerce.alaska.gov/web/cbpl/corporations.aspx',
      'businessLicenseRequired': true,
      'janitoralLicenseRequired': false,
      'bondRequired': false,
    },
    'requiredPostings': [
      {'name': 'Alaska Minimum Wage', 'url': 'https://labor.alaska.gov/lss/'},
    ],
    'taxFilingSchedule': [],
  },

  'AZ': {
    'stateCode': 'AZ',
    'stateName': 'Arizona',
    'effectiveYear': 2026,
    'minimumWage': 14.70,
    'tippedMinimumWage': 11.70,
    'overtimeThreshold': 40,
    'overtimeMultiplier': 1.5,
    'hasStateIncomeTax': true,
    'stateTaxType': 'flat',
    'stateTaxRate': 0.025,
    'stateWithholdingFormUrl': 'https://azdor.gov/forms/withholding-forms',
    'depositSchedule': 'quarterly',
    'sutaRateNew': 0.02,
    'sutaRateMin': 0.0008,
    'sutaRateMax': 0.207,
    'sutaWageCap': 8000,
    'sutaRegistrationUrl': 'https://des.az.gov/services/employment/unemployment-employer',
    'workersCompRequired': true,
    'workersCompCleaningRate': 0.032,
    'workersCompUrl': 'https://www.azica.gov/',
    'benefitsThresholdHours': 30,
    'paidSickLeave': {
      'required': true,
      'accrualRate': 0.033,
      'maxAnnual': 40,
      'carryover': true,
      'description': 'Prop 206: 1 hr per 30 hrs worked, up to 40 hrs/yr (under 15 EEs) or 24 hrs.',
    },
    'atWillEmployment': true,
    'rightToWork': true,
    'eVerifyRequired': true,
    'businessRegistration': {
      'secretaryOfStateUrl': 'https://azsos.gov/business',
      'businessLicenseRequired': true,
      'businessLicenseUrl': 'https://azsos.gov/business',
      'janitoralLicenseRequired': false,
      'bondRequired': false,
    },
    'requiredPostings': [
      {'name': 'AZ Minimum Wage Act', 'url': 'https://www.azica.gov/labor-minimum-wage-main-page'},
      {'name': 'AZ Workers Comp', 'url': 'https://www.azica.gov/'},
      {'name': 'AZ Earned Paid Sick Time', 'url': 'https://www.azica.gov/labor-earned-paid-sick-time-702'},
    ],
    'taxFilingSchedule': [
      {'formId': 'A1-QRT', 'name': 'Quarterly Withholding Return', 'frequency': 'quarterly'},
      {'formId': 'UC-018', 'name': 'Quarterly Wage Report', 'frequency': 'quarterly'},
    ],
  },

  'AR': {
    'stateCode': 'AR',
    'stateName': 'Arkansas',
    'effectiveYear': 2026,
    'minimumWage': 11.00,
    'overtimeThreshold': 40,
    'overtimeMultiplier': 1.5,
    'hasStateIncomeTax': true,
    'stateTaxType': 'graduated',
    'taxBrackets': [
      {'min': 0, 'max': 5099, 'rate': 0.02},
      {'min': 5099, 'max': 10299, 'rate': 0.04},
      {'min': 10299, 'max': 999999999, 'rate': 0.044},
    ],
    'sutaRateNew': 0.032,
    'sutaWageCap': 7000,
    'workersCompRequired': true,
    'workersCompExemptions': 'Employers with fewer than 3 employees exempt',
    'workersCompCleaningRate': 0.034,
    'paidSickLeave': {'required': false},
    'atWillEmployment': true,
    'rightToWork': true,
    'eVerifyRequired': false,
    'businessRegistration': {
      'secretaryOfStateUrl': 'https://www.sos.arkansas.gov/business-commercial-services-bcs',
      'janitoralLicenseRequired': false,
      'bondRequired': false,
    },
  },

  'CA': {
    'stateCode': 'CA',
    'stateName': 'California',
    'effectiveYear': 2026,
    'minimumWage': 16.50,
    'overtimeThreshold': 40,
    'overtimeMultiplier': 1.5,
    'dailyOvertimeThreshold': 8,
    'dailyDoubleTimeThreshold': 12,
    'hasStateIncomeTax': true,
    'stateTaxType': 'graduated',
    'taxBrackets': [
      {'min': 0, 'max': 10412, 'rate': 0.01},
      {'min': 10412, 'max': 24684, 'rate': 0.02},
      {'min': 24684, 'max': 38959, 'rate': 0.04},
      {'min': 38959, 'max': 54081, 'rate': 0.06},
      {'min': 54081, 'max': 68350, 'rate': 0.08},
      {'min': 68350, 'max': 349137, 'rate': 0.093},
      {'min': 349137, 'max': 418961, 'rate': 0.103},
      {'min': 418961, 'max': 698271, 'rate': 0.113},
      {'min': 698271, 'max': 999999999, 'rate': 0.123},
    ],
    'stateWithholdingFormUrl': 'https://edd.ca.gov/en/payroll_taxes/forms_and_publications/',
    'depositSchedule': 'semi-weekly',
    'sutaRateNew': 0.034,
    'sutaRateMin': 0.015,
    'sutaRateMax': 0.065,
    'sutaWageCap': 7000,
    'sutaRegistrationUrl': 'https://edd.ca.gov/en/payroll_taxes/',
    'workersCompRequired': true,
    'workersCompCleaningRate': 0.0312,
    'workersCompUrl': 'https://www.dir.ca.gov/dwc/',
    'benefitsThresholdHours': 30,
    'paidSickLeave': {
      'required': true,
      'accrualRate': 0.02,
      'maxAnnual': 48,
      'carryover': true,
      'description': 'Healthy Workplaces Act: 1 hr per 30 hrs worked, up to 48 hrs/yr.',
    },
    'paidFamilyLeave': {
      'available': true,
      'weeksDuration': 8,
      'wageReplacement': 0.60,
    },
    'requiredBreaks': {
      'mealAfterHours': 5,
      'mealDurationMinutes': 30,
      'restEveryHours': 4,
      'restDurationMinutes': 10,
    },
    'atWillEmployment': true,
    'rightToWork': false,
    'eVerifyRequired': false,
    'businessRegistration': {
      'secretaryOfStateUrl': 'https://www.sos.ca.gov/business-programs',
      'businessLicenseRequired': true,
      'businessLicenseUrl': 'https://www.sos.ca.gov/business-programs',
      'janitoralLicenseRequired': true,
      'janitoralLicenseUrl': 'https://www.dir.ca.gov/dlse/Janitorial_Contractors.html',
      'bondRequired': true,
      'bondMinimum': 150000,
    },
    'requiredPostings': [
      {'name': 'CA Minimum Wage', 'url': 'https://www.dir.ca.gov/iwc/MW-2025.pdf'},
      {'name': 'CA Paid Sick Leave', 'url': 'https://www.dir.ca.gov/dlse/Publications/Paid-Sick-Days-Poster.pdf'},
      {'name': 'CA Workers Comp', 'url': 'https://www.dir.ca.gov/dwc/'},
      {'name': 'CA Payday Notice', 'url': 'https://www.dir.ca.gov/dlse/'},
      {'name': 'CA DFEH Harassment', 'url': 'https://calcivilrights.ca.gov/'},
    ],
    'taxFilingSchedule': [
      {'formId': 'DE-9', 'name': 'Quarterly Contribution Return', 'frequency': 'quarterly'},
      {'formId': 'DE-9C', 'name': 'Quarterly Wage Detail', 'frequency': 'quarterly'},
    ],
  },

  'CO': {
    'stateCode': 'CO',
    'stateName': 'Colorado',
    'effectiveYear': 2026,
    'minimumWage': 14.81,
    'tippedMinimumWage': 11.79,
    'overtimeThreshold': 40,
    'overtimeMultiplier': 1.5,
    'hasStateIncomeTax': true,
    'stateTaxType': 'flat',
    'stateTaxRate': 0.044,
    'sutaRateNew': 0.0170,
    'sutaWageCap': 23800,
    'workersCompRequired': true,
    'workersCompCleaningRate': 0.029,
    'paidSickLeave': {
      'required': true,
      'maxAnnual': 48,
      'accrualRate': 0.033,
      'description': 'Healthy Families & Workplaces Act: 1 hr per 30 hrs worked.',
    },
    'paidFamilyLeave': {
      'available': true,
      'weeksDuration': 12,
      'wageReplacement': 0.90,
      'description': 'FAMLI Act: Up to 12 weeks, funded by payroll premiums.',
    },
    'atWillEmployment': true,
    'rightToWork': false,
    'eVerifyRequired': false,
    'businessRegistration': {
      'secretaryOfStateUrl': 'https://www.sos.state.co.us/pubs/business/',
      'janitoralLicenseRequired': false,
      'bondRequired': false,
    },
    'requiredPostings': [
      {'name': 'CO Minimum Wage', 'url': 'https://cdle.colorado.gov/'},
      {'name': 'CO Paid Sick Leave', 'url': 'https://cdle.colorado.gov/'},
    ],
  },

  'CT': {
    'stateCode': 'CT',
    'stateName': 'Connecticut',
    'effectiveYear': 2026,
    'minimumWage': 16.35,
    'overtimeThreshold': 40,
    'overtimeMultiplier': 1.5,
    'hasStateIncomeTax': true,
    'stateTaxType': 'graduated',
    'sutaRateNew': 0.030,
    'sutaWageCap': 15000,
    'workersCompRequired': true,
    'workersCompCleaningRate': 0.031,
    'paidSickLeave': {
      'required': true,
      'maxAnnual': 40,
      'description': 'Employers with 50+ must provide 40 hrs/yr.',
    },
    'paidFamilyLeave': {
      'available': true,
      'weeksDuration': 12,
      'wageReplacement': 0.95,
    },
    'atWillEmployment': true,
    'rightToWork': false,
    'businessRegistration': {
      'secretaryOfStateUrl': 'https://portal.ct.gov/SOTS/Business-Services',
      'janitoralLicenseRequired': false,
      'bondRequired': false,
    },
  },

  'DE': {
    'stateCode': 'DE',
    'stateName': 'Delaware',
    'effectiveYear': 2026,
    'minimumWage': 15.00,
    'overtimeThreshold': 40,
    'overtimeMultiplier': 1.5,
    'hasStateIncomeTax': true,
    'stateTaxType': 'graduated',
    'sutaRateNew': 0.012,
    'sutaWageCap': 10500,
    'workersCompRequired': true,
    'workersCompCleaningRate': 0.028,
    'paidSickLeave': {
      'required': true,
      'maxAnnual': 40,
      'description': 'Healthy Delaware Families Act: 1 hr per 30 hrs, employers 10+.',
    },
    'paidFamilyLeave': {
      'available': true,
      'weeksDuration': 12,
    },
    'atWillEmployment': true,
    'rightToWork': false,
    'businessRegistration': {
      'secretaryOfStateUrl': 'https://corp.delaware.gov/',
      'janitoralLicenseRequired': false,
      'bondRequired': false,
    },
  },

  'DC': {
    'stateCode': 'DC',
    'stateName': 'District of Columbia',
    'effectiveYear': 2026,
    'minimumWage': 17.50,
    'tippedMinimumWage': 10.00,
    'overtimeThreshold': 40,
    'overtimeMultiplier': 1.5,
    'hasStateIncomeTax': true,
    'stateTaxType': 'graduated',
    'sutaRateNew': 0.027,
    'sutaWageCap': 9000,
    'workersCompRequired': true,
    'workersCompCleaningRate': 0.034,
    'paidSickLeave': {
      'required': true,
      'maxAnnual': 56,
      'description': 'Accrued Sick & Safe Leave Act: up to 7 days/yr for 100+ employees.',
    },
    'paidFamilyLeave': {
      'available': true,
      'weeksDuration': 12,
      'wageReplacement': 0.90,
    },
    'atWillEmployment': true,
    'businessRegistration': {
      'secretaryOfStateUrl': 'https://dcra.dc.gov/',
      'janitoralLicenseRequired': false,
      'bondRequired': false,
    },
  },

  'FL': {
    'stateCode': 'FL',
    'stateName': 'Florida',
    'effectiveYear': 2026,
    'minimumWage': 15.00,
    'tippedMinimumWage': 11.98,
    'overtimeThreshold': 40,
    'overtimeMultiplier': 1.5,
    'hasStateIncomeTax': false,
    'stateTaxType': 'none',
    'sutaRateNew': 0.027,
    'sutaRateMin': 0.001,
    'sutaRateMax': 0.054,
    'sutaWageCap': 7000,
    'sutaRegistrationUrl': 'https://floridarevenue.com/taxes/taxesfees/Pages/reemployment.aspx',
    'workersCompRequired': true,
    'workersCompExemptions': 'Non-construction employers with fewer than 4 employees exempt',
    'workersCompCleaningRate': 0.026,
    'workersCompUrl': 'https://www.myfloridacfo.com/division/wc/',
    'paidSickLeave': {'required': false},
    'atWillEmployment': true,
    'rightToWork': true,
    'eVerifyRequired': true,
    'businessRegistration': {
      'secretaryOfStateUrl': 'https://dos.myflorida.com/sunbiz/',
      'businessLicenseRequired': true,
      'janitoralLicenseRequired': false,
      'bondRequired': false,
    },
    'requiredPostings': [
      {'name': 'FL Minimum Wage', 'url': 'https://floridajobs.org/'},
      {'name': 'FL Workers Comp', 'url': 'https://www.myfloridacfo.com/division/wc/'},
    ],
  },

  'GA': {
    'stateCode': 'GA',
    'stateName': 'Georgia',
    'effectiveYear': 2026,
    'minimumWage': 7.25,
    'overtimeThreshold': 40,
    'overtimeMultiplier': 1.5,
    'hasStateIncomeTax': true,
    'stateTaxType': 'flat',
    'stateTaxRate': 0.0549,
    'sutaRateNew': 0.027,
    'sutaWageCap': 9500,
    'workersCompRequired': true,
    'workersCompExemptions': 'Employers with fewer than 3 employees exempt',
    'workersCompCleaningRate': 0.030,
    'paidSickLeave': {'required': false},
    'atWillEmployment': true,
    'rightToWork': true,
    'eVerifyRequired': true,
    'businessRegistration': {
      'secretaryOfStateUrl': 'https://sos.ga.gov/corporations-division',
      'janitoralLicenseRequired': false,
      'bondRequired': false,
    },
  },

  'HI': {
    'stateCode': 'HI',
    'stateName': 'Hawaii',
    'effectiveYear': 2026,
    'minimumWage': 14.00,
    'overtimeThreshold': 40,
    'overtimeMultiplier': 1.5,
    'hasStateIncomeTax': true,
    'stateTaxType': 'graduated',
    'sutaRateNew': 0.040,
    'sutaWageCap': 59100,
    'workersCompRequired': true,
    'workersCompCleaningRate': 0.033,
    'paidSickLeave': {
      'required': true,
      'maxAnnual': 40,
      'description': 'Temporary Disability Insurance (TDI) required.',
    },
    'atWillEmployment': true,
    'rightToWork': false,
    'businessRegistration': {
      'secretaryOfStateUrl': 'https://cca.hawaii.gov/breg/',
      'janitoralLicenseRequired': false,
      'bondRequired': false,
    },
  },

  'ID': {
    'stateCode': 'ID',
    'stateName': 'Idaho',
    'effectiveYear': 2026,
    'minimumWage': 7.25,
    'overtimeThreshold': 40,
    'overtimeMultiplier': 1.5,
    'hasStateIncomeTax': true,
    'stateTaxType': 'flat',
    'stateTaxRate': 0.058,
    'sutaRateNew': 0.011,
    'sutaWageCap': 53500,
    'workersCompRequired': true,
    'workersCompCleaningRate': 0.027,
    'paidSickLeave': {'required': false},
    'atWillEmployment': true,
    'rightToWork': true,
    'businessRegistration': {
      'secretaryOfStateUrl': 'https://sos.idaho.gov/business/',
      'janitoralLicenseRequired': false,
      'bondRequired': false,
    },
  },

  'IL': {
    'stateCode': 'IL',
    'stateName': 'Illinois',
    'effectiveYear': 2026,
    'minimumWage': 15.00,
    'tippedMinimumWage': 9.00,
    'overtimeThreshold': 40,
    'overtimeMultiplier': 1.5,
    'hasStateIncomeTax': true,
    'stateTaxType': 'flat',
    'stateTaxRate': 0.0495,
    'sutaRateNew': 0.035,
    'sutaWageCap': 13590,
    'workersCompRequired': true,
    'workersCompCleaningRate': 0.031,
    'paidSickLeave': {
      'required': true,
      'maxAnnual': 40,
      'description': 'Paid Leave for All Workers Act: 40 hrs/yr for any reason.',
    },
    'atWillEmployment': true,
    'rightToWork': false,
    'eVerifyRequired': true,
    'businessRegistration': {
      'secretaryOfStateUrl': 'https://www.ilsos.gov/departments/business_services/',
      'janitoralLicenseRequired': false,
      'bondRequired': false,
    },
  },

  'IN': {'stateCode': 'IN', 'stateName': 'Indiana', 'effectiveYear': 2026, 'minimumWage': 7.25, 'hasStateIncomeTax': true, 'stateTaxType': 'flat', 'stateTaxRate': 0.0305, 'sutaRateNew': 0.025, 'sutaWageCap': 9500, 'workersCompRequired': true, 'workersCompCleaningRate': 0.028, 'paidSickLeave': {'required': false}, 'atWillEmployment': true, 'rightToWork': true, 'businessRegistration': {'secretaryOfStateUrl': 'https://www.in.gov/sos/business/', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'IA': {'stateCode': 'IA', 'stateName': 'Iowa', 'effectiveYear': 2026, 'minimumWage': 7.25, 'hasStateIncomeTax': true, 'stateTaxType': 'flat', 'stateTaxRate': 0.038, 'sutaRateNew': 0.010, 'sutaWageCap': 36100, 'workersCompRequired': true, 'workersCompCleaningRate': 0.025, 'paidSickLeave': {'required': false}, 'atWillEmployment': true, 'rightToWork': true, 'businessRegistration': {'secretaryOfStateUrl': 'https://sos.iowa.gov/business/', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'KS': {'stateCode': 'KS', 'stateName': 'Kansas', 'effectiveYear': 2026, 'minimumWage': 7.25, 'hasStateIncomeTax': true, 'stateTaxType': 'graduated', 'sutaRateNew': 0.027, 'sutaWageCap': 14000, 'workersCompRequired': true, 'workersCompCleaningRate': 0.029, 'paidSickLeave': {'required': false}, 'atWillEmployment': true, 'rightToWork': true, 'businessRegistration': {'secretaryOfStateUrl': 'https://www.sos.ks.gov/business/', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'KY': {'stateCode': 'KY', 'stateName': 'Kentucky', 'effectiveYear': 2026, 'minimumWage': 7.25, 'hasStateIncomeTax': true, 'stateTaxType': 'flat', 'stateTaxRate': 0.04, 'sutaRateNew': 0.027, 'sutaWageCap': 11400, 'workersCompRequired': true, 'workersCompCleaningRate': 0.032, 'paidSickLeave': {'required': false}, 'atWillEmployment': true, 'rightToWork': true, 'businessRegistration': {'secretaryOfStateUrl': 'https://www.sos.ky.gov/bus/', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'LA': {'stateCode': 'LA', 'stateName': 'Louisiana', 'effectiveYear': 2026, 'minimumWage': 7.25, 'hasStateIncomeTax': true, 'stateTaxType': 'flat', 'stateTaxRate': 0.0425, 'sutaRateNew': 0.029, 'sutaWageCap': 7700, 'workersCompRequired': true, 'workersCompCleaningRate': 0.033, 'paidSickLeave': {'required': false}, 'atWillEmployment': true, 'rightToWork': true, 'businessRegistration': {'secretaryOfStateUrl': 'https://www.sos.la.gov/BusinessServices/', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'ME': {'stateCode': 'ME', 'stateName': 'Maine', 'effectiveYear': 2026, 'minimumWage': 14.65, 'hasStateIncomeTax': true, 'stateTaxType': 'graduated', 'sutaRateNew': 0.024, 'sutaWageCap': 12000, 'workersCompRequired': true, 'workersCompCleaningRate': 0.030, 'paidSickLeave': {'required': true, 'maxAnnual': 40, 'description': 'Earned Paid Leave: 1 hr per 40 hrs, up to 40 hrs/yr.'}, 'atWillEmployment': true, 'rightToWork': false, 'businessRegistration': {'secretaryOfStateUrl': 'https://www.maine.gov/sos/cec/', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'MD': {'stateCode': 'MD', 'stateName': 'Maryland', 'effectiveYear': 2026, 'minimumWage': 15.00, 'hasStateIncomeTax': true, 'stateTaxType': 'graduated', 'sutaRateNew': 0.023, 'sutaWageCap': 8500, 'workersCompRequired': true, 'workersCompCleaningRate': 0.028, 'paidSickLeave': {'required': true, 'maxAnnual': 64, 'description': 'Healthy Working Families Act: 1 hr per 30 hrs, up to 64 hrs/yr.'}, 'paidFamilyLeave': {'available': true, 'weeksDuration': 12}, 'atWillEmployment': true, 'rightToWork': false, 'businessRegistration': {'secretaryOfStateUrl': 'https://sos.maryland.gov/Pages/BusinessFiling.aspx', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'MA': {'stateCode': 'MA', 'stateName': 'Massachusetts', 'effectiveYear': 2026, 'minimumWage': 15.00, 'hasStateIncomeTax': true, 'stateTaxType': 'flat', 'stateTaxRate': 0.05, 'sutaRateNew': 0.017, 'sutaWageCap': 15000, 'workersCompRequired': true, 'workersCompCleaningRate': 0.029, 'paidSickLeave': {'required': true, 'maxAnnual': 40, 'description': 'Earned Sick Time: 1 hr per 30 hrs, employers 11+.'}, 'paidFamilyLeave': {'available': true, 'weeksDuration': 26, 'wageReplacement': 0.80}, 'atWillEmployment': true, 'rightToWork': false, 'businessRegistration': {'secretaryOfStateUrl': 'https://www.sec.state.ma.us/cor/', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'MI': {'stateCode': 'MI', 'stateName': 'Michigan', 'effectiveYear': 2026, 'minimumWage': 12.48, 'hasStateIncomeTax': true, 'stateTaxType': 'flat', 'stateTaxRate': 0.0425, 'sutaRateNew': 0.027, 'sutaWageCap': 9500, 'workersCompRequired': true, 'workersCompCleaningRate': 0.030, 'paidSickLeave': {'required': true, 'maxAnnual': 72, 'description': 'Earned Sick Time Act: 1 hr per 30 hrs, up to 72 hrs/yr.'}, 'atWillEmployment': true, 'rightToWork': false, 'businessRegistration': {'secretaryOfStateUrl': 'https://www.michigan.gov/lara/bureau-list/bcs', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'MN': {'stateCode': 'MN', 'stateName': 'Minnesota', 'effectiveYear': 2026, 'minimumWage': 11.13, 'hasStateIncomeTax': true, 'stateTaxType': 'graduated', 'sutaRateNew': 0.028, 'sutaWageCap': 42000, 'workersCompRequired': true, 'workersCompCleaningRate': 0.031, 'paidSickLeave': {'required': true, 'maxAnnual': 48, 'description': 'Earned Sick and Safe Time: 1 hr per 30 hrs.'}, 'paidFamilyLeave': {'available': true, 'weeksDuration': 12}, 'atWillEmployment': true, 'rightToWork': false, 'businessRegistration': {'secretaryOfStateUrl': 'https://www.sos.state.mn.us/business-liens/', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'MS': {'stateCode': 'MS', 'stateName': 'Mississippi', 'effectiveYear': 2026, 'minimumWage': 7.25, 'hasStateIncomeTax': true, 'stateTaxType': 'flat', 'stateTaxRate': 0.05, 'sutaRateNew': 0.012, 'sutaWageCap': 14000, 'workersCompRequired': true, 'workersCompExemptions': 'Employers with fewer than 5 employees exempt', 'workersCompCleaningRate': 0.032, 'paidSickLeave': {'required': false}, 'atWillEmployment': true, 'rightToWork': true, 'eVerifyRequired': true, 'businessRegistration': {'secretaryOfStateUrl': 'https://www.sos.ms.gov/business-formation', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'MO': {'stateCode': 'MO', 'stateName': 'Missouri', 'effectiveYear': 2026, 'minimumWage': 15.00, 'hasStateIncomeTax': true, 'stateTaxType': 'graduated', 'sutaRateNew': 0.024, 'sutaWageCap': 10500, 'workersCompRequired': true, 'workersCompCleaningRate': 0.028, 'paidSickLeave': {'required': true, 'maxAnnual': 56, 'description': 'Prop A: 1 hr per 30 hrs, 56 hrs for 15+ employees.'}, 'atWillEmployment': true, 'rightToWork': false, 'businessRegistration': {'secretaryOfStateUrl': 'https://www.sos.mo.gov/business/', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'MT': {'stateCode': 'MT', 'stateName': 'Montana', 'effectiveYear': 2026, 'minimumWage': 10.55, 'hasStateIncomeTax': true, 'stateTaxType': 'flat', 'stateTaxRate': 0.059, 'sutaRateNew': 0.013, 'sutaWageCap': 43000, 'workersCompRequired': true, 'workersCompCleaningRate': 0.033, 'paidSickLeave': {'required': false}, 'atWillEmployment': false, 'rightToWork': false, 'businessRegistration': {'secretaryOfStateUrl': 'https://sosmt.gov/business/', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'NE': {'stateCode': 'NE', 'stateName': 'Nebraska', 'effectiveYear': 2026, 'minimumWage': 13.50, 'hasStateIncomeTax': true, 'stateTaxType': 'graduated', 'sutaRateNew': 0.012, 'sutaWageCap': 9000, 'workersCompRequired': true, 'workersCompCleaningRate': 0.027, 'paidSickLeave': {'required': true, 'maxAnnual': 56, 'description': 'Nebraska Healthy Families Act: 1 hr per 30 hrs.'}, 'atWillEmployment': true, 'rightToWork': true, 'businessRegistration': {'secretaryOfStateUrl': 'https://sos.nebraska.gov/business-services', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'NV': {'stateCode': 'NV', 'stateName': 'Nevada', 'effectiveYear': 2026, 'minimumWage': 12.00, 'hasStateIncomeTax': false, 'stateTaxType': 'none', 'sutaRateNew': 0.027, 'sutaWageCap': 40600, 'workersCompRequired': true, 'workersCompCleaningRate': 0.029, 'paidSickLeave': {'required': true, 'maxAnnual': 40, 'description': 'SB 312: 0.01923 hrs per hr worked, up to 40 hrs/yr.'}, 'atWillEmployment': true, 'rightToWork': true, 'businessRegistration': {'secretaryOfStateUrl': 'https://www.nvsos.gov/sos/businesses', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'NH': {'stateCode': 'NH', 'stateName': 'New Hampshire', 'effectiveYear': 2026, 'minimumWage': 7.25, 'hasStateIncomeTax': false, 'stateTaxType': 'none', 'sutaRateNew': 0.027, 'sutaWageCap': 14000, 'workersCompRequired': true, 'workersCompCleaningRate': 0.030, 'paidSickLeave': {'required': false}, 'atWillEmployment': true, 'rightToWork': false, 'businessRegistration': {'secretaryOfStateUrl': 'https://www.sos.nh.gov/corporation-division', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'NJ': {'stateCode': 'NJ', 'stateName': 'New Jersey', 'effectiveYear': 2026, 'minimumWage': 15.49, 'hasStateIncomeTax': true, 'stateTaxType': 'graduated', 'sutaRateNew': 0.026, 'sutaWageCap': 42300, 'workersCompRequired': true, 'workersCompCleaningRate': 0.031, 'paidSickLeave': {'required': true, 'maxAnnual': 40, 'description': 'NJ Earned Sick Leave: 1 hr per 30 hrs.'}, 'paidFamilyLeave': {'available': true, 'weeksDuration': 12, 'wageReplacement': 0.85}, 'atWillEmployment': true, 'rightToWork': false, 'businessRegistration': {'secretaryOfStateUrl': 'https://www.njportal.com/DOR/BusinessFormation', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'NM': {'stateCode': 'NM', 'stateName': 'New Mexico', 'effectiveYear': 2026, 'minimumWage': 12.00, 'hasStateIncomeTax': true, 'stateTaxType': 'graduated', 'sutaRateNew': 0.027, 'sutaWageCap': 30800, 'workersCompRequired': true, 'workersCompCleaningRate': 0.030, 'paidSickLeave': {'required': true, 'maxAnnual': 64, 'description': 'Healthy Workplaces Act: 1 hr per 30 hrs.'}, 'atWillEmployment': true, 'rightToWork': false, 'businessRegistration': {'secretaryOfStateUrl': 'https://portal.sos.state.nm.us/BFS/', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'NY': {'stateCode': 'NY', 'stateName': 'New York', 'effectiveYear': 2026, 'minimumWage': 16.50, 'tippedMinimumWage': 11.00, 'overtimeThreshold': 40, 'overtimeMultiplier': 1.5, 'hasStateIncomeTax': true, 'stateTaxType': 'graduated', 'taxBrackets': [{'min': 0, 'max': 8500, 'rate': 0.04}, {'min': 8500, 'max': 11700, 'rate': 0.045}, {'min': 11700, 'max': 13900, 'rate': 0.0525}, {'min': 13900, 'max': 80650, 'rate': 0.055}, {'min': 80650, 'max': 215400, 'rate': 0.06}, {'min': 215400, 'max': 1077550, 'rate': 0.0685}, {'min': 1077550, 'max': 999999999, 'rate': 0.109}], 'sutaRateNew': 0.041, 'sutaWageCap': 12500, 'workersCompRequired': true, 'workersCompCleaningRate': 0.035, 'paidSickLeave': {'required': true, 'maxAnnual': 56, 'description': 'NYS Paid Sick Leave: 40-56 hrs based on employer size.'}, 'paidFamilyLeave': {'available': true, 'weeksDuration': 12, 'wageReplacement': 0.67}, 'atWillEmployment': true, 'rightToWork': false, 'businessRegistration': {'secretaryOfStateUrl': 'https://dos.ny.gov/corporations-state-records-division', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'NC': {'stateCode': 'NC', 'stateName': 'North Carolina', 'effectiveYear': 2026, 'minimumWage': 7.25, 'hasStateIncomeTax': true, 'stateTaxType': 'flat', 'stateTaxRate': 0.045, 'sutaRateNew': 0.010, 'sutaWageCap': 29600, 'workersCompRequired': true, 'workersCompExemptions': 'Employers with fewer than 3 employees exempt', 'workersCompCleaningRate': 0.028, 'paidSickLeave': {'required': false}, 'atWillEmployment': true, 'rightToWork': true, 'eVerifyRequired': true, 'businessRegistration': {'secretaryOfStateUrl': 'https://www.sosnc.gov/divisions/business_registration', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'ND': {'stateCode': 'ND', 'stateName': 'North Dakota', 'effectiveYear': 2026, 'minimumWage': 7.25, 'hasStateIncomeTax': true, 'stateTaxType': 'flat', 'stateTaxRate': 0.0195, 'sutaRateNew': 0.011, 'sutaWageCap': 43800, 'workersCompRequired': true, 'workersCompCleaningRate': 0.025, 'paidSickLeave': {'required': false}, 'atWillEmployment': true, 'rightToWork': true, 'businessRegistration': {'secretaryOfStateUrl': 'https://sos.nd.gov/business/', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'OH': {'stateCode': 'OH', 'stateName': 'Ohio', 'effectiveYear': 2026, 'minimumWage': 10.65, 'hasStateIncomeTax': true, 'stateTaxType': 'graduated', 'sutaRateNew': 0.027, 'sutaWageCap': 9000, 'workersCompRequired': true, 'workersCompCleaningRate': 0.030, 'paidSickLeave': {'required': false}, 'atWillEmployment': true, 'rightToWork': false, 'businessRegistration': {'secretaryOfStateUrl': 'https://www.ohiosos.gov/businesses/', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'OK': {'stateCode': 'OK', 'stateName': 'Oklahoma', 'effectiveYear': 2026, 'minimumWage': 7.25, 'hasStateIncomeTax': true, 'stateTaxType': 'flat', 'stateTaxRate': 0.0475, 'sutaRateNew': 0.015, 'sutaWageCap': 27000, 'workersCompRequired': true, 'workersCompCleaningRate': 0.031, 'paidSickLeave': {'required': false}, 'atWillEmployment': true, 'rightToWork': true, 'businessRegistration': {'secretaryOfStateUrl': 'https://www.sos.ok.gov/business/', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'OR': {'stateCode': 'OR', 'stateName': 'Oregon', 'effectiveYear': 2026, 'minimumWage': 14.70, 'overtimeThreshold': 40, 'overtimeMultiplier': 1.5, 'hasStateIncomeTax': true, 'stateTaxType': 'graduated', 'sutaRateNew': 0.025, 'sutaWageCap': 52000, 'workersCompRequired': true, 'workersCompCleaningRate': 0.031, 'paidSickLeave': {'required': true, 'maxAnnual': 40, 'description': 'Oregon Sick Time: 1 hr per 30 hrs, employers with 10+.'}, 'paidFamilyLeave': {'available': true, 'weeksDuration': 12, 'wageReplacement': 1.0}, 'atWillEmployment': true, 'rightToWork': false, 'businessRegistration': {'secretaryOfStateUrl': 'https://sos.oregon.gov/business/', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'PA': {'stateCode': 'PA', 'stateName': 'Pennsylvania', 'effectiveYear': 2026, 'minimumWage': 7.25, 'hasStateIncomeTax': true, 'stateTaxType': 'flat', 'stateTaxRate': 0.0307, 'sutaRateNew': 0.036, 'sutaWageCap': 10000, 'workersCompRequired': true, 'workersCompCleaningRate': 0.032, 'paidSickLeave': {'required': false, 'description': 'Philadelphia and Pittsburgh have local sick leave ordinances.'}, 'atWillEmployment': true, 'rightToWork': false, 'businessRegistration': {'secretaryOfStateUrl': 'https://www.dos.pa.gov/BusinessCharities/', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'RI': {'stateCode': 'RI', 'stateName': 'Rhode Island', 'effectiveYear': 2026, 'minimumWage': 15.00, 'hasStateIncomeTax': true, 'stateTaxType': 'graduated', 'sutaRateNew': 0.014, 'sutaWageCap': 28200, 'workersCompRequired': true, 'workersCompCleaningRate': 0.029, 'paidSickLeave': {'required': true, 'maxAnnual': 40, 'description': 'Healthy and Safe Families Act: 1 hr per 35 hrs.'}, 'paidFamilyLeave': {'available': true, 'weeksDuration': 6}, 'atWillEmployment': true, 'rightToWork': false, 'businessRegistration': {'secretaryOfStateUrl': 'https://www.sos.ri.gov/divisions/business-services', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'SC': {'stateCode': 'SC', 'stateName': 'South Carolina', 'effectiveYear': 2026, 'minimumWage': 7.25, 'hasStateIncomeTax': true, 'stateTaxType': 'graduated', 'sutaRateNew': 0.019, 'sutaWageCap': 14000, 'workersCompRequired': true, 'workersCompExemptions': 'Employers with fewer than 4 employees exempt', 'workersCompCleaningRate': 0.028, 'paidSickLeave': {'required': false}, 'atWillEmployment': true, 'rightToWork': true, 'eVerifyRequired': true, 'businessRegistration': {'secretaryOfStateUrl': 'https://www.sos.sc.gov/online-filings', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'SD': {'stateCode': 'SD', 'stateName': 'South Dakota', 'effectiveYear': 2026, 'minimumWage': 11.45, 'hasStateIncomeTax': false, 'stateTaxType': 'none', 'sutaRateNew': 0.012, 'sutaWageCap': 15000, 'workersCompRequired': true, 'workersCompCleaningRate': 0.026, 'paidSickLeave': {'required': false}, 'atWillEmployment': true, 'rightToWork': true, 'businessRegistration': {'secretaryOfStateUrl': 'https://sdsos.gov/business-services/', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'TN': {'stateCode': 'TN', 'stateName': 'Tennessee', 'effectiveYear': 2026, 'minimumWage': 7.25, 'hasStateIncomeTax': false, 'stateTaxType': 'none', 'sutaRateNew': 0.027, 'sutaWageCap': 7000, 'workersCompRequired': true, 'workersCompExemptions': 'Employers with fewer than 5 employees exempt', 'workersCompCleaningRate': 0.029, 'paidSickLeave': {'required': false}, 'atWillEmployment': true, 'rightToWork': true, 'eVerifyRequired': true, 'businessRegistration': {'secretaryOfStateUrl': 'https://sos.tn.gov/business-services', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'TX': {'stateCode': 'TX', 'stateName': 'Texas', 'effectiveYear': 2026, 'minimumWage': 7.25, 'hasStateIncomeTax': false, 'stateTaxType': 'none', 'sutaRateNew': 0.027, 'sutaRateMin': 0.001, 'sutaRateMax': 0.064, 'sutaWageCap': 9000, 'sutaRegistrationUrl': 'https://www.twc.texas.gov/businesses/unemployment-tax', 'workersCompRequired': false, 'workersCompExemptions': 'Workers comp is voluntary in Texas', 'workersCompCleaningRate': 0.028, 'workersCompUrl': 'https://www.tdi.texas.gov/wc/', 'paidSickLeave': {'required': false, 'description': 'Austin, Dallas, and San Antonio passed local ordinances but enforcement is stayed.'}, 'atWillEmployment': true, 'rightToWork': true, 'eVerifyRequired': true, 'businessRegistration': {'secretaryOfStateUrl': 'https://www.sos.state.tx.us/corp/', 'businessLicenseUrl': 'https://www.sos.state.tx.us/corp/', 'janitoralLicenseRequired': false, 'bondRequired': false}, 'requiredPostings': [{'name': 'TX Payday Law', 'url': 'https://www.twc.texas.gov/'}, {'name': 'TX Workers Comp Notice', 'url': 'https://www.tdi.texas.gov/wc/'}], 'taxFilingSchedule': [{'formId': 'C-3', 'name': 'Employer Quarterly Report', 'frequency': 'quarterly'}]},

  'UT': {'stateCode': 'UT', 'stateName': 'Utah', 'effectiveYear': 2026, 'minimumWage': 7.25, 'hasStateIncomeTax': true, 'stateTaxType': 'flat', 'stateTaxRate': 0.0465, 'sutaRateNew': 0.012, 'sutaWageCap': 44800, 'workersCompRequired': true, 'workersCompCleaningRate': 0.027, 'paidSickLeave': {'required': false}, 'atWillEmployment': true, 'rightToWork': true, 'eVerifyRequired': true, 'businessRegistration': {'secretaryOfStateUrl': 'https://corporations.utah.gov/', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'VT': {'stateCode': 'VT', 'stateName': 'Vermont', 'effectiveYear': 2026, 'minimumWage': 14.01, 'hasStateIncomeTax': true, 'stateTaxType': 'graduated', 'sutaRateNew': 0.010, 'sutaWageCap': 14100, 'workersCompRequired': true, 'workersCompCleaningRate': 0.030, 'paidSickLeave': {'required': true, 'maxAnnual': 40, 'description': 'Earned Sick Time: 1 hr per 52 hrs worked, up to 40 hrs/yr.'}, 'paidFamilyLeave': {'available': true, 'weeksDuration': 6}, 'atWillEmployment': true, 'rightToWork': false, 'businessRegistration': {'secretaryOfStateUrl': 'https://sos.vermont.gov/corporations/', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'VA': {'stateCode': 'VA', 'stateName': 'Virginia', 'effectiveYear': 2026, 'minimumWage': 13.50, 'hasStateIncomeTax': true, 'stateTaxType': 'graduated', 'sutaRateNew': 0.024, 'sutaWageCap': 8000, 'workersCompRequired': true, 'workersCompExemptions': 'Employers with fewer than 2 employees may be exempt', 'workersCompCleaningRate': 0.028, 'paidSickLeave': {'required': false}, 'atWillEmployment': true, 'rightToWork': true, 'businessRegistration': {'secretaryOfStateUrl': 'https://www.scc.virginia.gov/pages/Business-Entity-Search', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'WA': {'stateCode': 'WA', 'stateName': 'Washington', 'effectiveYear': 2026, 'minimumWage': 16.66, 'overtimeThreshold': 40, 'overtimeMultiplier': 1.5, 'hasStateIncomeTax': false, 'stateTaxType': 'none', 'sutaRateNew': 0.028, 'sutaWageCap': 68500, 'workersCompRequired': true, 'workersCompCleaningRate': 0.032, 'paidSickLeave': {'required': true, 'maxAnnual': 40, 'accrualRate': 0.033, 'description': 'Paid Sick Leave: 1 hr per 40 hrs worked.'}, 'paidFamilyLeave': {'available': true, 'weeksDuration': 18, 'wageReplacement': 0.90}, 'atWillEmployment': true, 'rightToWork': false, 'businessRegistration': {'secretaryOfStateUrl': 'https://www.sos.wa.gov/corporations-charities/', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'WV': {'stateCode': 'WV', 'stateName': 'West Virginia', 'effectiveYear': 2026, 'minimumWage': 8.75, 'hasStateIncomeTax': true, 'stateTaxType': 'graduated', 'sutaRateNew': 0.027, 'sutaWageCap': 9000, 'workersCompRequired': true, 'workersCompCleaningRate': 0.032, 'paidSickLeave': {'required': false}, 'atWillEmployment': true, 'rightToWork': true, 'businessRegistration': {'secretaryOfStateUrl': 'https://sos.wv.gov/business/', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'WI': {'stateCode': 'WI', 'stateName': 'Wisconsin', 'effectiveYear': 2026, 'minimumWage': 7.25, 'hasStateIncomeTax': true, 'stateTaxType': 'graduated', 'sutaRateNew': 0.025, 'sutaWageCap': 14000, 'workersCompRequired': true, 'workersCompExemptions': 'Employers with fewer than 3 employees exempt', 'workersCompCleaningRate': 0.029, 'paidSickLeave': {'required': false}, 'atWillEmployment': true, 'rightToWork': true, 'businessRegistration': {'secretaryOfStateUrl': 'https://www.wdfi.org/corporations/', 'janitoralLicenseRequired': false, 'bondRequired': false}},

  'WY': {'stateCode': 'WY', 'stateName': 'Wyoming', 'effectiveYear': 2026, 'minimumWage': 7.25, 'hasStateIncomeTax': false, 'stateTaxType': 'none', 'sutaRateNew': 0.012, 'sutaWageCap': 30900, 'workersCompRequired': true, 'workersCompCleaningRate': 0.027, 'paidSickLeave': {'required': false}, 'atWillEmployment': true, 'rightToWork': true, 'businessRegistration': {'secretaryOfStateUrl': 'https://sos.wyo.gov/Business/', 'janitoralLicenseRequired': false, 'bondRequired': false}},
};
