// lib/features/compliance/seed/tax_source_catalog_data.dart
//
// Authoritative source URLs for every tax data point used in the system.
// AI monitoring agents use this catalog to detect when values change.
//
// Each entry maps a logical data key to:
//   sourceUrl   — the canonical URL to check
//   sourceType  — 'pdf', 'webpage', 'api', 'portal'
//   dataPath    — human description of where the value lives in the source
//   checkSchedule — 'annual_nov', 'annual_jan', 'quarterly', 'monthly'
//   category    — groups related sources for batch crawling
//   description — what this source provides

const Map<String, Map<String, dynamic>> kTaxSourceCatalog = {
  // ════════════════════════════════════════════════════════════════
  // FEDERAL SOURCES
  // ════════════════════════════════════════════════════════════════

  'fed_withholding_tables': {
    'category': 'federal',
    'description': 'Federal income tax withholding brackets and rates',
    'sourceUrl': 'https://www.irs.gov/pub/irs-pdf/p15t.pdf',
    'sourceType': 'pdf',
    'dataPath': 'Percentage Method Tables, pp. 6-8',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['federalRule'],
    'affectsFields': [
      'taxBracketsSingle',
      'taxBracketsMarried',
      'standardDeductions',
    ],
    'notes': 'IRS publishes Pub 15-T each December for the following year. '
        'Check starting mid-November for draft versions.',
  },
  'fed_circular_e': {
    'category': 'federal',
    'description': 'Employer tax guide — deposit rules, FICA rates, wage bases',
    'sourceUrl': 'https://www.irs.gov/pub/irs-pdf/p15.pdf',
    'sourceType': 'pdf',
    'dataPath': 'Social Security/Medicare rates (Sec. 1), deposit rules (Sec. 11)',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['federalRule'],
    'affectsFields': [
      'socialSecurityRate',
      'socialSecurityWageCap',
      'medicareRate',
      'additionalMedicareRate',
      'additionalMedicareThreshold',
    ],
  },
  'fed_ss_wage_base': {
    'category': 'federal',
    'description': 'Social Security taxable wage base announcement',
    'sourceUrl':
        'https://www.ssa.gov/oact/cola/cbb.html',
    'sourceType': 'webpage',
    'dataPath': 'Contribution and Benefit Base table',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['federalRule'],
    'affectsFields': ['socialSecurityWageCap'],
    'notes': 'SSA announces the new wage base each October.',
  },
  'fed_futa_rate': {
    'category': 'federal',
    'description': 'FUTA tax rate and wage cap',
    'sourceUrl': 'https://www.irs.gov/taxtopics/tc759',
    'sourceType': 'webpage',
    'dataPath': 'FUTA Tax Rate and Wage Base section',
    'checkSchedule': 'annual_jan',
    'affectsCollections': ['federalRule'],
    'affectsFields': ['futaRate', 'futaWageCap'],
  },
  'fed_minimum_wage': {
    'category': 'federal',
    'description': 'Federal minimum wage',
    'sourceUrl': 'https://www.dol.gov/agencies/whd/minimum-wage',
    'sourceType': 'webpage',
    'dataPath': 'Current federal minimum wage rate',
    'checkSchedule': 'monthly',
    'affectsCollections': ['federalRule'],
    'affectsFields': ['federalMinimumWage'],
    'notes': 'Rarely changes but legislation can move at any time.',
  },
  'fed_aca_threshold': {
    'category': 'federal',
    'description': 'ACA full-time employee threshold for benefits',
    'sourceUrl':
        'https://www.irs.gov/affordable-care-act/employers/identifying-full-time-employees',
    'sourceType': 'webpage',
    'dataPath': 'Full-time employee definition section',
    'checkSchedule': 'annual_jan',
    'affectsCollections': ['federalRule'],
    'affectsFields': ['acaBenefitsThreshold'],
  },
  'fed_form_941': {
    'category': 'federal',
    'description': 'Form 941 instructions and due dates',
    'sourceUrl': 'https://www.irs.gov/forms-pubs/about-form-941',
    'sourceType': 'webpage',
    'dataPath': 'Filing deadlines and instructions link',
    'checkSchedule': 'quarterly',
    'affectsCollections': ['federalRule'],
    'affectsFields': ['taxFilingSchedule'],
  },
  'fed_w2_deadline': {
    'category': 'federal',
    'description': 'W-2/W-3 filing deadline and instructions',
    'sourceUrl': 'https://www.irs.gov/forms-pubs/about-form-w-2',
    'sourceType': 'webpage',
    'dataPath': 'Due date and electronic filing requirements',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['federalRule'],
    'affectsFields': ['taxFilingSchedule'],
  },

  // ════════════════════════════════════════════════════════════════
  // STATE TAX AGENCY MASTER SOURCES
  // ════════════════════════════════════════════════════════════════
  // Each state entry points to the agency page where withholding
  // tables, rates, and employer guides are published.

  'state_AL': {
    'category': 'state_withholding',
    'stateCode': 'AL',
    'description': 'Alabama withholding tax tables and employer guide',
    'sourceUrl': 'https://www.revenue.alabama.gov/individual-corporate/taxes-administered-by-individual-corporate-income-tax/withholding-tax/',
    'sourceType': 'webpage',
    'dataPath': 'Withholding tax tables and employer guide PDF',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['taxBrackets', 'stateTaxRate'],
  },
  'state_AK': {
    'category': 'state_withholding',
    'stateCode': 'AK',
    'description': 'Alaska — no state income tax',
    'sourceUrl': 'https://labor.alaska.gov/estax/',
    'sourceType': 'webpage',
    'dataPath': 'Employer tax information (SUI only)',
    'checkSchedule': 'annual_jan',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['sutaRateNew', 'sutaWageCap'],
    'notes': 'No state income tax. Only SUI rates change.',
  },
  'state_AZ': {
    'category': 'state_withholding',
    'stateCode': 'AZ',
    'description': 'Arizona flat income tax rate and withholding',
    'sourceUrl': 'https://azdor.gov/businesses-arizona/withholding-tax',
    'sourceType': 'webpage',
    'dataPath': 'Withholding percentage tables',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['stateTaxRate'],
  },
  'state_AR': {
    'category': 'state_withholding',
    'stateCode': 'AR',
    'description': 'Arkansas withholding tables',
    'sourceUrl': 'https://www.dfa.arkansas.gov/income-tax/withholding-tax-branch/',
    'sourceType': 'webpage',
    'dataPath': 'Employer withholding tables PDF',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['taxBrackets'],
  },
  'state_CA': {
    'category': 'state_withholding',
    'stateCode': 'CA',
    'description': 'California withholding schedules (DE 44)',
    'sourceUrl': 'https://edd.ca.gov/en/payroll_taxes/rates_and_withholding/',
    'sourceType': 'webpage',
    'dataPath': 'California Employer Guide (DE 44) PDF link',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['taxBrackets', 'sdiRate'],
  },
  'state_CO': {
    'category': 'state_withholding',
    'stateCode': 'CO',
    'description': 'Colorado flat income tax rate',
    'sourceUrl': 'https://tax.colorado.gov/withholding-tax',
    'sourceType': 'webpage',
    'dataPath': 'Withholding rate and tables',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['stateTaxRate'],
  },
  'state_CT': {
    'category': 'state_withholding',
    'stateCode': 'CT',
    'description': 'Connecticut withholding tables',
    'sourceUrl': 'https://portal.ct.gov/DRS/Businesses/New-Business-Tax-Information/Withholding-Tax',
    'sourceType': 'webpage',
    'dataPath': 'Withholding calculation rules and tables',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['taxBrackets'],
  },
  'state_DE': {
    'category': 'state_withholding',
    'stateCode': 'DE',
    'description': 'Delaware withholding tables',
    'sourceUrl': 'https://revenue.delaware.gov/employers/',
    'sourceType': 'webpage',
    'dataPath': 'Withholding tax rates and tables',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['taxBrackets'],
  },
  'state_FL': {
    'category': 'state_withholding',
    'stateCode': 'FL',
    'description': 'Florida — no state income tax (SUI only)',
    'sourceUrl': 'https://floridarevenue.com/taxes/taxesfees/Pages/reemploy.aspx',
    'sourceType': 'webpage',
    'dataPath': 'Reemployment tax rates',
    'checkSchedule': 'annual_jan',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['sutaRateNew', 'sutaWageCap'],
  },
  'state_GA': {
    'category': 'state_withholding',
    'stateCode': 'GA',
    'description': 'Georgia withholding tax guide',
    'sourceUrl': 'https://dor.georgia.gov/taxes/business-taxes/withholding-tax',
    'sourceType': 'webpage',
    'dataPath': 'Employer withholding guide and tables',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['taxBrackets', 'stateTaxRate'],
  },
  'state_HI': {
    'category': 'state_withholding',
    'stateCode': 'HI',
    'description': 'Hawaii withholding tables',
    'sourceUrl': 'https://tax.hawaii.gov/forms/a1_b3_5whhold/',
    'sourceType': 'webpage',
    'dataPath': 'Booklet A employer withholding tables',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['taxBrackets'],
  },
  'state_ID': {
    'category': 'state_withholding',
    'stateCode': 'ID',
    'description': 'Idaho withholding guide',
    'sourceUrl': 'https://tax.idaho.gov/i-1026.cfm',
    'sourceType': 'webpage',
    'dataPath': 'Idaho employer withholding tables',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['stateTaxRate'],
  },
  'state_IL': {
    'category': 'state_withholding',
    'stateCode': 'IL',
    'description': 'Illinois flat income tax rate',
    'sourceUrl': 'https://tax.illinois.gov/businesses/withholdingincome.html',
    'sourceType': 'webpage',
    'dataPath': 'Current withholding rate',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['stateTaxRate'],
  },
  'state_IN': {
    'category': 'state_withholding',
    'stateCode': 'IN',
    'description': 'Indiana state + county withholding rates',
    'sourceUrl': 'https://www.in.gov/dor/business-tax/withholding-tax/',
    'sourceType': 'webpage',
    'dataPath': 'County tax rates table (Departmental Notice #1)',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule', 'taxJurisdiction'],
    'affectsFields': ['stateTaxRate', 'countyRates'],
    'notes': 'Indiana has county-level income taxes. Rates change annually.',
  },
  'state_IA': {
    'category': 'state_withholding',
    'stateCode': 'IA',
    'description': 'Iowa withholding tables',
    'sourceUrl': 'https://tax.iowa.gov/withholding-tax',
    'sourceType': 'webpage',
    'dataPath': 'Iowa withholding formula and tables',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['taxBrackets'],
  },
  'state_KS': {
    'category': 'state_withholding',
    'stateCode': 'KS',
    'description': 'Kansas withholding tables',
    'sourceUrl': 'https://www.ksrevenue.gov/bustaxtypeswhempl.html',
    'sourceType': 'webpage',
    'dataPath': 'Kansas withholding tax guide (KW-100)',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['taxBrackets'],
  },
  'state_KY': {
    'category': 'state_withholding',
    'stateCode': 'KY',
    'description': 'Kentucky flat income tax and local occupational taxes',
    'sourceUrl': 'https://revenue.ky.gov/Business/Withholding-Tax/Pages/default.aspx',
    'sourceType': 'webpage',
    'dataPath': 'Withholding rate, local occupational tax info',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule', 'taxJurisdiction'],
    'affectsFields': ['stateTaxRate'],
  },
  'state_LA': {
    'category': 'state_withholding',
    'stateCode': 'LA',
    'description': 'Louisiana withholding tables',
    'sourceUrl': 'https://revenue.louisiana.gov/Businesses/WithholdingTax',
    'sourceType': 'webpage',
    'dataPath': 'Withholding tables and employer guide',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['taxBrackets'],
  },
  'state_ME': {
    'category': 'state_withholding',
    'stateCode': 'ME',
    'description': 'Maine withholding tables',
    'sourceUrl': 'https://www.maine.gov/revenue/taxes/withholding',
    'sourceType': 'webpage',
    'dataPath': 'Maine employer withholding guide',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['taxBrackets'],
  },
  'state_MD': {
    'category': 'state_withholding',
    'stateCode': 'MD',
    'description': 'Maryland state + county withholding',
    'sourceUrl': 'https://www.marylandtaxes.gov/business/income/withholding/index.php',
    'sourceType': 'webpage',
    'dataPath': 'State and county withholding rates, MW507 tables',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule', 'taxJurisdiction'],
    'affectsFields': ['taxBrackets', 'countyRates'],
    'notes': 'Maryland has county-level "piggyback" taxes on top of state rates.',
  },
  'state_MA': {
    'category': 'state_withholding',
    'stateCode': 'MA',
    'description': 'Massachusetts flat income tax rate',
    'sourceUrl': 'https://www.mass.gov/info-details/withholding-tax',
    'sourceType': 'webpage',
    'dataPath': 'Withholding rate and Circular M',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['stateTaxRate'],
  },
  'state_MI': {
    'category': 'state_withholding',
    'stateCode': 'MI',
    'description': 'Michigan state + city income taxes',
    'sourceUrl': 'https://www.michigan.gov/taxes/business-taxes/withholding',
    'sourceType': 'webpage',
    'dataPath': 'State rate and city income tax list',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule', 'taxJurisdiction'],
    'affectsFields': ['stateTaxRate', 'cityRates'],
    'notes': 'Michigan has ~24 cities with local income taxes.',
  },
  'state_MN': {
    'category': 'state_withholding',
    'stateCode': 'MN',
    'description': 'Minnesota withholding tables',
    'sourceUrl': 'https://www.revenue.state.mn.us/withholding-tax',
    'sourceType': 'webpage',
    'dataPath': 'Withholding tax tables and instructions',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['taxBrackets'],
  },
  'state_MS': {
    'category': 'state_withholding',
    'stateCode': 'MS',
    'description': 'Mississippi withholding tables',
    'sourceUrl': 'https://www.dor.ms.gov/Business/Pages/Withholding-Tax.aspx',
    'sourceType': 'webpage',
    'dataPath': 'Withholding tax tables',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['taxBrackets'],
  },
  'state_MO': {
    'category': 'state_withholding',
    'stateCode': 'MO',
    'description': 'Missouri withholding tables',
    'sourceUrl': 'https://dor.mo.gov/taxation/business/tax-types/withholding/',
    'sourceType': 'webpage',
    'dataPath': 'Withholding formula and tax tables',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['taxBrackets'],
  },
  'state_MT': {
    'category': 'state_withholding',
    'stateCode': 'MT',
    'description': 'Montana withholding tables',
    'sourceUrl': 'https://mtrevenue.gov/taxes/wage-withholding/',
    'sourceType': 'webpage',
    'dataPath': 'Withholding tables and guide',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['taxBrackets'],
  },
  'state_NE': {
    'category': 'state_withholding',
    'stateCode': 'NE',
    'description': 'Nebraska withholding tables',
    'sourceUrl': 'https://revenue.nebraska.gov/businesses/withholding-income-tax',
    'sourceType': 'webpage',
    'dataPath': 'Circular EN withholding tables',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['taxBrackets'],
  },
  'state_NV': {
    'category': 'state_withholding',
    'stateCode': 'NV',
    'description': 'Nevada — no state income tax (SUI only)',
    'sourceUrl': 'https://ui.nv.gov/EMPLOYER/EmployerHomePage.html',
    'sourceType': 'webpage',
    'dataPath': 'Employer unemployment tax rates',
    'checkSchedule': 'annual_jan',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['sutaRateNew', 'sutaWageCap'],
  },
  'state_NH': {
    'category': 'state_withholding',
    'stateCode': 'NH',
    'description': 'New Hampshire — no wage income tax',
    'sourceUrl': 'https://www.nhes.nh.gov/services/employers/',
    'sourceType': 'webpage',
    'dataPath': 'Employer tax information (SUI only)',
    'checkSchedule': 'annual_jan',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['sutaRateNew', 'sutaWageCap'],
  },
  'state_NJ': {
    'category': 'state_withholding',
    'stateCode': 'NJ',
    'description': 'New Jersey withholding tables',
    'sourceUrl': 'https://www.nj.gov/treasury/taxation/freqqite.shtml',
    'sourceType': 'webpage',
    'dataPath': 'NJ-WT withholding tables',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['taxBrackets'],
  },
  'state_NM': {
    'category': 'state_withholding',
    'stateCode': 'NM',
    'description': 'New Mexico withholding tables',
    'sourceUrl': 'https://www.tax.newmexico.gov/businesses/withholding-tax/',
    'sourceType': 'webpage',
    'dataPath': 'FYI-104 withholding tax information',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['taxBrackets'],
  },
  'state_NY': {
    'category': 'state_withholding',
    'stateCode': 'NY',
    'description': 'New York withholding tables + Yonkers/NYC',
    'sourceUrl': 'https://www.tax.ny.gov/bus/wt/wtidx.htm',
    'sourceType': 'webpage',
    'dataPath': 'NYS-50-T withholding tables',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule', 'taxJurisdiction'],
    'affectsFields': ['taxBrackets'],
    'notes': 'NYC and Yonkers have separate withholding requirements.',
  },
  'state_NC': {
    'category': 'state_withholding',
    'stateCode': 'NC',
    'description': 'North Carolina flat income tax rate',
    'sourceUrl': 'https://www.ncdor.gov/taxes-forms/withholding-tax',
    'sourceType': 'webpage',
    'dataPath': 'Current withholding rate and tables',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['stateTaxRate'],
  },
  'state_ND': {
    'category': 'state_withholding',
    'stateCode': 'ND',
    'description': 'North Dakota withholding tables',
    'sourceUrl': 'https://www.tax.nd.gov/business/income-tax-withholding',
    'sourceType': 'webpage',
    'dataPath': 'Withholding rates and tables',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['taxBrackets'],
  },
  'state_OH': {
    'category': 'state_withholding',
    'stateCode': 'OH',
    'description': 'Ohio state withholding + municipal income taxes',
    'sourceUrl': 'https://tax.ohio.gov/employer-withholding',
    'sourceType': 'webpage',
    'dataPath': 'Withholding tables, municipal tax info',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule', 'taxJurisdiction'],
    'affectsFields': ['taxBrackets'],
    'notes': 'Ohio has ~600 municipalities with local income taxes. RITA and CCA are the main collectors.',
  },
  'state_OH_rita': {
    'category': 'local_tax',
    'stateCode': 'OH',
    'description': 'Ohio RITA municipal tax rates',
    'sourceUrl': 'https://www.ritaohio.com/TaxRatesTable',
    'sourceType': 'webpage',
    'dataPath': 'Tax rates table by municipality',
    'checkSchedule': 'annual_jan',
    'affectsCollections': ['taxJurisdiction'],
    'affectsFields': ['rate'],
  },
  'state_OH_cca': {
    'category': 'local_tax',
    'stateCode': 'OH',
    'description': 'Ohio CCA municipal tax rates',
    'sourceUrl': 'https://www.ccatax.ci.cleveland.oh.us/',
    'sourceType': 'webpage',
    'dataPath': 'Member municipality rates',
    'checkSchedule': 'annual_jan',
    'affectsCollections': ['taxJurisdiction'],
    'affectsFields': ['rate'],
  },
  'state_OK': {
    'category': 'state_withholding',
    'stateCode': 'OK',
    'description': 'Oklahoma withholding tables',
    'sourceUrl': 'https://oklahoma.gov/tax/businesses/withholding-tax.html',
    'sourceType': 'webpage',
    'dataPath': 'Withholding tax tables and guide',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['taxBrackets'],
  },
  'state_OR': {
    'category': 'state_withholding',
    'stateCode': 'OR',
    'description': 'Oregon withholding tables + transit tax',
    'sourceUrl': 'https://www.oregon.gov/dor/programs/businesses/pages/payroll-withholding.aspx',
    'sourceType': 'webpage',
    'dataPath': 'Withholding tables and statewide transit tax rate',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule', 'taxJurisdiction'],
    'affectsFields': ['taxBrackets'],
    'notes': 'Oregon has a statewide transit tax (0.1%) plus some local taxes.',
  },
  'state_PA': {
    'category': 'state_withholding',
    'stateCode': 'PA',
    'description': 'Pennsylvania flat income tax + local EIT rates',
    'sourceUrl': 'https://www.revenue.pa.gov/TaxTypes/EmployerWithholding/Pages/default.aspx',
    'sourceType': 'webpage',
    'dataPath': 'State flat rate and Act 32 local EIT rates',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule', 'taxJurisdiction'],
    'affectsFields': ['stateTaxRate'],
    'notes': 'PA has ~2,500 municipalities with local earned income tax collected through ~70 Act 32 tax officers.',
  },
  'state_PA_eit': {
    'category': 'local_tax',
    'stateCode': 'PA',
    'description': 'Pennsylvania local EIT rates by municipality',
    'sourceUrl': 'https://dced.pa.gov/local-government/act-32-local-income-tax-information/',
    'sourceType': 'webpage',
    'dataPath': 'Act 32 EIT rate table (Excel download)',
    'checkSchedule': 'annual_jan',
    'affectsCollections': ['taxJurisdiction'],
    'affectsFields': ['rate'],
  },
  'state_RI': {
    'category': 'state_withholding',
    'stateCode': 'RI',
    'description': 'Rhode Island withholding tables',
    'sourceUrl': 'https://tax.ri.gov/tax-sections/employer-tax',
    'sourceType': 'webpage',
    'dataPath': 'Withholding tax tables',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['taxBrackets'],
  },
  'state_SC': {
    'category': 'state_withholding',
    'stateCode': 'SC',
    'description': 'South Carolina withholding tables',
    'sourceUrl': 'https://dor.sc.gov/tax/withholding',
    'sourceType': 'webpage',
    'dataPath': 'Withholding tax tables and formula',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['taxBrackets'],
  },
  'state_SD': {
    'category': 'state_withholding',
    'stateCode': 'SD',
    'description': 'South Dakota — no state income tax',
    'sourceUrl': 'https://dlr.sd.gov/unemployment_insurance/ui_employers.aspx',
    'sourceType': 'webpage',
    'dataPath': 'Employer SUI rates',
    'checkSchedule': 'annual_jan',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['sutaRateNew', 'sutaWageCap'],
  },
  'state_TN': {
    'category': 'state_withholding',
    'stateCode': 'TN',
    'description': 'Tennessee — no wage income tax',
    'sourceUrl': 'https://www.tn.gov/workforce/employers/tax-and-insurance.html',
    'sourceType': 'webpage',
    'dataPath': 'Employer SUI information',
    'checkSchedule': 'annual_jan',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['sutaRateNew', 'sutaWageCap'],
  },
  'state_TX': {
    'category': 'state_withholding',
    'stateCode': 'TX',
    'description': 'Texas — no state income tax (SUI only)',
    'sourceUrl': 'https://www.twc.texas.gov/businesses/unemployment-tax',
    'sourceType': 'webpage',
    'dataPath': 'Employer UI tax rates and wage base',
    'checkSchedule': 'annual_jan',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['sutaRateNew', 'sutaWageCap'],
  },
  'state_UT': {
    'category': 'state_withholding',
    'stateCode': 'UT',
    'description': 'Utah flat income tax rate',
    'sourceUrl': 'https://tax.utah.gov/withholding',
    'sourceType': 'webpage',
    'dataPath': 'Withholding rate and Publication 14',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['stateTaxRate'],
  },
  'state_VT': {
    'category': 'state_withholding',
    'stateCode': 'VT',
    'description': 'Vermont withholding tables',
    'sourceUrl': 'https://tax.vermont.gov/business/withholding',
    'sourceType': 'webpage',
    'dataPath': 'Withholding tax tables and instructions',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['taxBrackets'],
  },
  'state_VA': {
    'category': 'state_withholding',
    'stateCode': 'VA',
    'description': 'Virginia withholding tables',
    'sourceUrl': 'https://www.tax.virginia.gov/withholding-tax',
    'sourceType': 'webpage',
    'dataPath': 'Employer withholding tables',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['taxBrackets'],
  },
  'state_WA': {
    'category': 'state_withholding',
    'stateCode': 'WA',
    'description': 'Washington — no state income tax (SUI + WA Cares)',
    'sourceUrl': 'https://esd.wa.gov/employer-taxes',
    'sourceType': 'webpage',
    'dataPath': 'Employer SUI rates and WA Cares Fund rate',
    'checkSchedule': 'annual_jan',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['sutaRateNew', 'sutaWageCap'],
    'notes': 'WA has no income tax but has WA Cares Fund (long-term care) payroll tax.',
  },
  'state_WV': {
    'category': 'state_withholding',
    'stateCode': 'WV',
    'description': 'West Virginia withholding tables',
    'sourceUrl': 'https://tax.wv.gov/Business/Withholding/Pages/WithholdingTax.aspx',
    'sourceType': 'webpage',
    'dataPath': 'Withholding tax tables and guide',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['taxBrackets'],
  },
  'state_WI': {
    'category': 'state_withholding',
    'stateCode': 'WI',
    'description': 'Wisconsin withholding tables',
    'sourceUrl': 'https://www.revenue.wi.gov/Pages/ISE/Withholding.aspx',
    'sourceType': 'webpage',
    'dataPath': 'Publication W-166 withholding tables',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['taxBrackets'],
  },
  'state_WY': {
    'category': 'state_withholding',
    'stateCode': 'WY',
    'description': 'Wyoming — no state income tax',
    'sourceUrl': 'https://dws.wyo.gov/employers/',
    'sourceType': 'webpage',
    'dataPath': 'Employer UI tax rates',
    'checkSchedule': 'annual_jan',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['sutaRateNew', 'sutaWageCap'],
  },
  'state_DC': {
    'category': 'state_withholding',
    'stateCode': 'DC',
    'description': 'District of Columbia withholding tables',
    'sourceUrl': 'https://otr.cfo.dc.gov/page/employer-withholding',
    'sourceType': 'webpage',
    'dataPath': 'DC withholding tax tables',
    'checkSchedule': 'annual_nov',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['taxBrackets'],
  },

  // ════════════════════════════════════════════════════════════════
  // SUI RATE SOURCES (states where SUI is the primary employer tax)
  // ════════════════════════════════════════════════════════════════

  'sui_rate_lookup': {
    'category': 'sui',
    'description': 'US DOL state UI tax rate comparison chart',
    'sourceUrl':
        'https://oui.doleta.gov/unemploy/topics.asp',
    'sourceType': 'webpage',
    'dataPath': 'State unemployment insurance tax data by state',
    'checkSchedule': 'annual_jan',
    'affectsCollections': ['stateRule'],
    'affectsFields': ['sutaRateNew', 'sutaRateMin', 'sutaRateMax', 'sutaWageCap'],
    'notes': 'DOL publishes a comparison chart. Individual state sites are more authoritative.',
  },

  // ════════════════════════════════════════════════════════════════
  // LOCAL TAX AGGREGATE SOURCES
  // ════════════════════════════════════════════════════════════════

  'local_in_county': {
    'category': 'local_tax',
    'stateCode': 'IN',
    'description': 'Indiana county income tax rates',
    'sourceUrl': 'https://www.in.gov/dor/tax-forms/county-tax-information/',
    'sourceType': 'webpage',
    'dataPath': 'Departmental Notice #1 — county rates table',
    'checkSchedule': 'annual_jan',
    'affectsCollections': ['taxJurisdiction'],
    'affectsFields': ['rate'],
  },
  'local_md_county': {
    'category': 'local_tax',
    'stateCode': 'MD',
    'description': 'Maryland county piggyback income tax rates',
    'sourceUrl': 'https://www.marylandtaxes.gov/individual/tax-compliance/individual-tax-types/county-tax-rates.php',
    'sourceType': 'webpage',
    'dataPath': 'County tax rate table',
    'checkSchedule': 'annual_jan',
    'affectsCollections': ['taxJurisdiction'],
    'affectsFields': ['rate'],
  },
  'local_mi_city': {
    'category': 'local_tax',
    'stateCode': 'MI',
    'description': 'Michigan city income tax rates',
    'sourceUrl': 'https://www.michigan.gov/taxes/business-taxes/city-income-tax/city-income-tax-rates',
    'sourceType': 'webpage',
    'dataPath': 'City income tax rate table',
    'checkSchedule': 'annual_jan',
    'affectsCollections': ['taxJurisdiction'],
    'affectsFields': ['rate', 'nonResidentRate'],
  },
  'local_ky_occupational': {
    'category': 'local_tax',
    'stateCode': 'KY',
    'description': 'Kentucky local occupational license tax rates',
    'sourceUrl': 'https://revenue.ky.gov/Property/Occupational-Taxes/Pages/default.aspx',
    'sourceType': 'webpage',
    'dataPath': 'Occupational tax rate listing by locality',
    'checkSchedule': 'annual_jan',
    'affectsCollections': ['taxJurisdiction'],
    'affectsFields': ['rate'],
  },
};
