// lib/features/compliance/seed/jurisdictions/ohio_city_rates.dart
//
// Ohio: ~600 municipalities levy a municipal income tax.
// This file covers the top ~200 cities by population (covers >90% of
// commercial cleaning activity in the state).
// Source: Ohio Department of Taxation, Municipal Income Tax Rates.
// Effective 2025/2026 tax year.
//
// Ohio municipal income tax is based on WHERE THE WORK IS PERFORMED,
// which is critical for cleaning companies with mobile workforces.
// Most cities allow a credit for taxes paid to other cities (up to their rate).

const Map<String, Map<String, dynamic>> kOhioCityRates = {
  // ═══ Major metros ═══
  'OH_AKRON':           {'name': 'Akron',           'rate': 0.025,  'creditRate': 0.025, 'type': 'city'},
  'OH_ALLIANCE':        {'name': 'Alliance',        'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_AMHERST':         {'name': 'Amherst',         'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_ASHLAND':         {'name': 'Ashland',         'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_ASHTABULA':       {'name': 'Ashtabula',       'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_ATHENS':          {'name': 'Athens',           'rate': 0.018,  'creditRate': 0.018, 'type': 'city'},
  'OH_AURORA':          {'name': 'Aurora',           'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_AVON':            {'name': 'Avon',             'rate': 0.0175, 'creditRate': 0.0175,'type': 'city'},
  'OH_AVON_LAKE':       {'name': 'Avon Lake',       'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_BARBERTON':       {'name': 'Barberton',       'rate': 0.025,  'creditRate': 0.025, 'type': 'city'},
  'OH_BAY_VILLAGE':     {'name': 'Bay Village',     'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_BEACHWOOD':       {'name': 'Beachwood',       'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_BEAVERCREEK':     {'name': 'Beavercreek',     'rate': 0.0175, 'creditRate': 0.0175,'type': 'city'},
  'OH_BEDFORD':         {'name': 'Bedford',          'rate': 0.025,  'creditRate': 0.015, 'type': 'city'},
  'OH_BELLEFONTAINE':   {'name': 'Bellefontaine',   'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_BEREA':           {'name': 'Berea',            'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_BOARDMAN':        {'name': 'Boardman',        'rate': 0.0225, 'creditRate': 0.0225,'type': 'city'},
  'OH_BOWLING_GREEN':   {'name': 'Bowling Green',   'rate': 0.02,   'creditRate': 0.01,  'type': 'city'},
  'OH_BROADVIEW_HTS':   {'name': 'Broadview Heights','rate': 0.02,  'creditRate': 0.02,  'type': 'city'},
  'OH_BROOK_PARK':      {'name': 'Brook Park',      'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_BRUNSWICK':       {'name': 'Brunswick',       'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_BUCYRUS':         {'name': 'Bucyrus',         'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_CAMBRIDGE':       {'name': 'Cambridge',       'rate': 0.02,   'creditRate': 0.01,  'type': 'city'},
  'OH_CANAL_FULTON':    {'name': 'Canal Fulton',    'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_CANTON':          {'name': 'Canton',           'rate': 0.025,  'creditRate': 0.025, 'type': 'city'},
  'OH_CELINA':          {'name': 'Celina',           'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_CENTERVILLE':     {'name': 'Centerville',     'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_CHILLICOTHE':     {'name': 'Chillicothe',     'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_CINCINNATI':      {'name': 'Cincinnati',      'rate': 0.018,  'creditRate': 0.018, 'type': 'city'},
  'OH_CIRCLEVILLE':     {'name': 'Circleville',     'rate': 0.018,  'creditRate': 0.018, 'type': 'city'},
  'OH_CLEVELAND':       {'name': 'Cleveland',       'rate': 0.025,  'creditRate': 0.025, 'type': 'city'},
  'OH_CLEVELAND_HTS':   {'name': 'Cleveland Heights','rate': 0.0225,'creditRate': 0.015, 'type': 'city'},
  'OH_COLUMBUS':        {'name': 'Columbus',        'rate': 0.025,  'creditRate': 0.025, 'type': 'city'},
  'OH_CONNEAUT':        {'name': 'Conneaut',        'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_COPLEY':          {'name': 'Copley',           'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_COSHOCTON':       {'name': 'Coshocton',       'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_CUYAHOGA_FALLS':  {'name': 'Cuyahoga Falls',  'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_DAYTON':          {'name': 'Dayton',           'rate': 0.025,  'creditRate': 0.025, 'type': 'city'},
  'OH_DEFIANCE':        {'name': 'Defiance',        'rate': 0.0175, 'creditRate': 0.01,  'type': 'city'},
  'OH_DELAWARE':        {'name': 'Delaware',        'rate': 0.019,  'creditRate': 0.019, 'type': 'city'},
  'OH_DOVER':           {'name': 'Dover',            'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_DUBLIN':          {'name': 'Dublin',           'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_EAST_CLEVELAND':  {'name': 'East Cleveland',  'rate': 0.02,   'creditRate': 0.015, 'type': 'city'},
  'OH_EAST_LIVERPOOL':  {'name': 'East Liverpool',  'rate': 0.02,   'creditRate': 0.01,  'type': 'city'},
  'OH_ELYRIA':          {'name': 'Elyria',           'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_EUCLID':          {'name': 'Euclid',           'rate': 0.029,  'creditRate': 0.02,  'type': 'city'},
  'OH_FAIRBORN':        {'name': 'Fairborn',        'rate': 0.02,   'creditRate': 0.015, 'type': 'city'},
  'OH_FAIRFIELD':       {'name': 'Fairfield',       'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_FAIRLAWN':        {'name': 'Fairlawn',        'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_FAIRVIEW_PARK':   {'name': 'Fairview Park',   'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_FINDLAY':         {'name': 'Findlay',          'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_FOSTORIA':        {'name': 'Fostoria',        'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_FREMONT':         {'name': 'Fremont',          'rate': 0.015,  'creditRate': 0.01,  'type': 'city'},
  'OH_GAHANNA':         {'name': 'Gahanna',         'rate': 0.025,  'creditRate': 0.025, 'type': 'city'},
  'OH_GALION':          {'name': 'Galion',           'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_GARFIELD_HTS':    {'name': 'Garfield Heights','rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_GREEN':           {'name': 'Green',            'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_GREENVILLE':      {'name': 'Greenville',      'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_GROVE_CITY':      {'name': 'Grove City',      'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_HAMILTON':        {'name': 'Hamilton',         'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_HILLIARD':        {'name': 'Hilliard',        'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_HUBER_HEIGHTS':   {'name': 'Huber Heights',   'rate': 0.025,  'creditRate': 0.025, 'type': 'city'},
  'OH_HUDSON':          {'name': 'Hudson',           'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_IRONTON':         {'name': 'Ironton',          'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_KENT':            {'name': 'Kent',             'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_KETTERING':       {'name': 'Kettering',       'rate': 0.025,  'creditRate': 0.0225,'type': 'city'},
  'OH_LAKEWOOD':        {'name': 'Lakewood',        'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_LANCASTER':       {'name': 'Lancaster',       'rate': 0.018,  'creditRate': 0.015, 'type': 'city'},
  'OH_LEBANON':         {'name': 'Lebanon',          'rate': 0.01,   'creditRate': 0.01,  'type': 'city'},
  'OH_LIMA':            {'name': 'Lima',             'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_LORAIN':          {'name': 'Lorain',           'rate': 0.025,  'creditRate': 0.015, 'type': 'city'},
  'OH_LOUISVILLE':      {'name': 'Louisville',      'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_LYNDHURST':       {'name': 'Lyndhurst',       'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_MANSFIELD':       {'name': 'Mansfield',       'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_MAPLE_HEIGHTS':   {'name': 'Maple Heights',   'rate': 0.025,  'creditRate': 0.02,  'type': 'city'},
  'OH_MARIETTA':        {'name': 'Marietta',        'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_MARION':          {'name': 'Marion',           'rate': 0.02,   'creditRate': 0.01,  'type': 'city'},
  'OH_MARYSVILLE':      {'name': 'Marysville',      'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_MASON':           {'name': 'Mason',            'rate': 0.012,  'creditRate': 0.012, 'type': 'city'},
  'OH_MASSILLON':       {'name': 'Massillon',       'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_MAUMEE':          {'name': 'Maumee',           'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_MAYFIELD_HTS':    {'name': 'Mayfield Heights','rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_MEDINA':          {'name': 'Medina',           'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_MENTOR':          {'name': 'Mentor',           'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_MIAMISBURG':      {'name': 'Miamisburg',      'rate': 0.0175, 'creditRate': 0.0175,'type': 'city'},
  'OH_MIDDLEBURG_HTS':  {'name': 'Middleburg Heights','rate': 0.02, 'creditRate': 0.02,  'type': 'city'},
  'OH_MIDDLETOWN':      {'name': 'Middletown',      'rate': 0.019,  'creditRate': 0.019, 'type': 'city'},
  'OH_MILFORD':         {'name': 'Milford',          'rate': 0.01,   'creditRate': 0.01,  'type': 'city'},
  'OH_MORAINE':         {'name': 'Moraine',          'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_MOUNT_VERNON':    {'name': 'Mount Vernon',    'rate': 0.02,   'creditRate': 0.01,  'type': 'city'},
  'OH_NAPOLEON':        {'name': 'Napoleon',        'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_NEW_PHILADELPHIA':{'name': 'New Philadelphia','rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_NEWARK':          {'name': 'Newark',           'rate': 0.0175, 'creditRate': 0.0175,'type': 'city'},
  'OH_NILES':           {'name': 'Niles',            'rate': 0.02,   'creditRate': 0.01,  'type': 'city'},
  'OH_NORTH_CANTON':    {'name': 'North Canton',    'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_NORTH_OLMSTED':   {'name': 'North Olmsted',   'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_NORTH_RIDGEVILLE':{'name': 'North Ridgeville','rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_NORTH_ROYALTON':  {'name': 'North Royalton',  'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_NORWOOD':         {'name': 'Norwood',          'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_OBERLIN':         {'name': 'Oberlin',          'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_OLMSTED_FALLS':   {'name': 'Olmsted Falls',   'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_ONTARIO':         {'name': 'Ontario',          'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_OREGON':          {'name': 'Oregon',           'rate': 0.025,  'creditRate': 0.025, 'type': 'city'},
  'OH_ORRVILLE':        {'name': 'Orrville',        'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_PAINESVILLE':     {'name': 'Painesville',     'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_PARMA':           {'name': 'Parma',            'rate': 0.025,  'creditRate': 0.025, 'type': 'city'},
  'OH_PARMA_HEIGHTS':   {'name': 'Parma Heights',   'rate': 0.03,   'creditRate': 0.03,  'type': 'city'},
  'OH_PATASKALA':       {'name': 'Pataskala',       'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_PERRYSBURG':      {'name': 'Perrysburg',      'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_PICKERINGTON':    {'name': 'Pickerington',    'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_PIQUA':           {'name': 'Piqua',            'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_PORTSMOUTH':      {'name': 'Portsmouth',      'rate': 0.015,  'creditRate': 0.0,   'type': 'city'},
  'OH_POWELL':          {'name': 'Powell',           'rate': 0.0075, 'creditRate': 0.0075,'type': 'city'},
  'OH_RAVENNA':         {'name': 'Ravenna',          'rate': 0.02,   'creditRate': 0.015, 'type': 'city'},
  'OH_REYNOLDSBURG':    {'name': 'Reynoldsburg',    'rate': 0.025,  'creditRate': 0.025, 'type': 'city'},
  'OH_RICHMOND_HTS':    {'name': 'Richmond Heights','rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_ROCKY_RIVER':     {'name': 'Rocky River',     'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_ROSSFORD':        {'name': 'Rossford',        'rate': 0.025,  'creditRate': 0.025, 'type': 'city'},
  'OH_SALEM':           {'name': 'Salem',            'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_SANDUSKY':        {'name': 'Sandusky',        'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_SHAKER_HEIGHTS':  {'name': 'Shaker Heights',  'rate': 0.0225, 'creditRate': 0.015, 'type': 'city'},
  'OH_SHARONVILLE':     {'name': 'Sharonville',     'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_SHELBY':          {'name': 'Shelby',           'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_SIDNEY':          {'name': 'Sidney',           'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_SOLON':           {'name': 'Solon',            'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_SOUTH_EUCLID':    {'name': 'South Euclid',    'rate': 0.02,   'creditRate': 0.015, 'type': 'city'},
  'OH_SPRINGBORO':      {'name': 'Springboro',      'rate': 0.01,   'creditRate': 0.01,  'type': 'city'},
  'OH_SPRINGFIELD':     {'name': 'Springfield',     'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_STEUBENVILLE':    {'name': 'Steubenville',    'rate': 0.02,   'creditRate': 0.01,  'type': 'city'},
  'OH_STOW':            {'name': 'Stow',             'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_STRONGSVILLE':    {'name': 'Strongsville',    'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_SYLVANIA':        {'name': 'Sylvania',        'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_TALLMADGE':       {'name': 'Tallmadge',       'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_TIFFIN':          {'name': 'Tiffin',           'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_TIPP_CITY':       {'name': 'Tipp City',       'rate': 0.015,  'creditRate': 0.0,   'type': 'city'},
  'OH_TOLEDO':          {'name': 'Toledo',           'rate': 0.025,  'creditRate': 0.025, 'type': 'city'},
  'OH_TROTWOOD':        {'name': 'Trotwood',        'rate': 0.025,  'creditRate': 0.025, 'type': 'city'},
  'OH_TROY':            {'name': 'Troy',             'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_TWINSBURG':       {'name': 'Twinsburg',       'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_UNIVERSITY_HTS':  {'name': 'University Heights','rate': 0.025,'creditRate': 0.015, 'type': 'city'},
  'OH_UPPER_ARLINGTON':  {'name': 'Upper Arlington',  'rate': 0.025, 'creditRate': 0.025, 'type': 'city'},
  'OH_UPPER_SANDUSKY':  {'name': 'Upper Sandusky',  'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_URBANA':          {'name': 'Urbana',           'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_VAN_WERT':        {'name': 'Van Wert',        'rate': 0.0125, 'creditRate': 0.0125,'type': 'city'},
  'OH_VANDALIA':        {'name': 'Vandalia',        'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_VERMILION':       {'name': 'Vermilion',       'rate': 0.01,   'creditRate': 0.01,  'type': 'city'},
  'OH_WADSWORTH':       {'name': 'Wadsworth',       'rate': 0.0125, 'creditRate': 0.0125,'type': 'city'},
  'OH_WAPAKONETA':      {'name': 'Wapakoneta',      'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_WARREN':          {'name': 'Warren',           'rate': 0.025,  'creditRate': 0.01,  'type': 'city'},
  'OH_WARRENSVILLE_HTS':{'name': 'Warrensville Heights','rate': 0.025,'creditRate': 0.015,'type': 'city'},
  'OH_WASHINGTON_CH':   {'name': 'Washington Court House','rate': 0.015,'creditRate': 0.015,'type': 'city'},
  'OH_WESTERVILLE':     {'name': 'Westerville',     'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_WESTLAKE':        {'name': 'Westlake',        'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_WHITEHALL':       {'name': 'Whitehall',       'rate': 0.025,  'creditRate': 0.025, 'type': 'city'},
  'OH_WILLOUGHBY':      {'name': 'Willoughby',      'rate': 0.02,   'creditRate': 0.02,  'type': 'city'},
  'OH_WILMINGTON':      {'name': 'Wilmington',      'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_WOOSTER':         {'name': 'Wooster',          'rate': 0.015,  'creditRate': 0.015, 'type': 'city'},
  'OH_WORTHINGTON':     {'name': 'Worthington',     'rate': 0.025,  'creditRate': 0.025, 'type': 'city'},
  'OH_XENIA':           {'name': 'Xenia',            'rate': 0.025,  'creditRate': 0.025, 'type': 'city'},
  'OH_YOUNGSTOWN':      {'name': 'Youngstown',      'rate': 0.025,  'creditRate': 0.025, 'type': 'city'},
  'OH_ZANESVILLE':      {'name': 'Zanesville',      'rate': 0.02,   'creditRate': 0.01,  'type': 'city'},
};
